/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import Others.*;
import Classes.*;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author dinis
 */
public class AddUserFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddUserFrame
     */
    static Point initialClick;

    String admId;
    String admName;
    
    String userId;
    String fName;
    String uid;
    String lName;
    String nic;
    String ctn1;
    String ctn2;
    String email;
    String sal;
    String addr1;
    String addr2;

    public AddUserFrame(String userRole, String uid, String fname, String lname, String nic, String ctn1, String ctn2, String email,
            String salary, String addr1, String addr2, String admId, String admName) {

        initComponents();

        this.fName = fname;
        this.uid = uid;
        this.lName = lname;
        this.nic = nic;
        this.ctn1 = ctn1;
        this.ctn2 = ctn2;
        this.email = email;
        this.sal = salary;
        this.addr1 = addr1;
        this.addr2 = addr2;

        this.admId = admId;
        this.admName = admName;
        
        time();
        IncrementUserId();
        upDetailsSet();
        dateLable.setText(DateTime.showDate());
        userRoleTxtBox.setText(userRole);
    }

    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    public void IncrementUserId() {

        userId = "USER-1000";
        try {
            String getID = "Select * from user";
            ResultSet rs = MyConn.search(getID);
            while (rs.next()) {

                String id = rs.getString("user_id");
                String splitId[] = id.split("-");
                int lastVal = Integer.parseInt(splitId[1]);
                lastVal++;
                userId = "USER-" + lastVal;

            }

            userIdTxtBox.setText(userId);
            userIdTxtBox.disable();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void upDetailsSet() {

        if (!(fName.equals(""))) {

            userIdTxtBox.setText(uid);
            fNameTxtBox1.setText(fName);
            lNameTxtBox.setText(lName);
            contactTxtBox01.setText(ctn1);
            contactTxtBox02.setText(ctn2);
            addrTxtBox1.setText(addr1);
            addrTxtBox2.setText(addr2);
            salaryTxtBox.setText(sal);
            emailTxtBox1.setText(email);
            nicTxtBox.setText(nic);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        minimizeLable = new javax.swing.JLabel();
        closeLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        userIdTxtBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userRoleTxtBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nicTxtBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        contactTxtBox01 = new javax.swing.JTextField();
        contactTxtBox02 = new javax.swing.JTextField();
        salaryTxtBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        updateUserBtn = new javax.swing.JButton();
        saveUserBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        vChkBox = new javax.swing.JCheckBox();
        lNameTxtBox = new javax.swing.JTextField();
        addrTxtBox2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fNameTxtBox1 = new javax.swing.JTextField();
        addrTxtBox1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emailTxtBox1 = new javax.swing.JTextField();
        menuPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        updateProfileBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uNameLable = new javax.swing.JLabel();
        uIDLable = new javax.swing.JLabel();
        inventoryDetailsBtn = new javax.swing.JButton();
        billTerminaBtn1 = new javax.swing.JButton();
        uDetailsBtn = new javax.swing.JButton();
        setMenuBtn = new javax.swing.JButton();
        suppDetailsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        clockInBtn = new javax.swing.JButton();
        clockOffBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 222, 179));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_16px.png"))); // NOI18N
        minimizeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLableMouseExited(evt);
            }
        });
        jPanel3.add(minimizeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 1, 30, 28));

        closeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_16px.png"))); // NOI18N
        closeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLableMouseExited(evt);
            }
        });
        jPanel3.add(closeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1259, 1, 30, 28));

        timeLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 150, 30));

        dateLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        jPanel1.setBackground(new java.awt.Color(242, 224, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(245, 222, 179));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add / Edit User Details");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        userIdTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        userIdTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdTxtBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("User ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Last Name");

        jPanel4.setBackground(new java.awt.Color(245, 222, 179));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("User Role :");

        userRoleTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        userRoleTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRoleTxtBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 199, Short.MAX_VALUE))
                    .addComponent(userRoleTxtBox))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userRoleTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("※ For new users, their password will be auto generated and login credentials will be sent to their email.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("NIC Number");

        nicTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nicTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicTxtBoxActionPerformed(evt);
            }
        });
        nicTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nicTxtBoxKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Address Line 02");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Contact Number(s)");

        contactTxtBox01.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contactTxtBox01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTxtBox01ActionPerformed(evt);
            }
        });
        contactTxtBox01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactTxtBox01KeyTyped(evt);
            }
        });

        contactTxtBox02.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contactTxtBox02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTxtBox02ActionPerformed(evt);
            }
        });
        contactTxtBox02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactTxtBox02KeyTyped(evt);
            }
        });

        salaryTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        salaryTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryTxtBoxActionPerformed(evt);
            }
        });
        salaryTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salaryTxtBoxKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Salary");

        updateUserBtn.setBackground(new java.awt.Color(204, 255, 153));
        updateUserBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateUserBtn.setText("Update Details");
        updateUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateUserBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateUserBtnMouseExited(evt);
            }
        });
        updateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserBtnActionPerformed(evt);
            }
        });

        saveUserBtn.setBackground(new java.awt.Color(102, 255, 102));
        saveUserBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveUserBtn.setText("Save Details");
        saveUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveUserBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveUserBtnMouseExited(evt);
            }
        });
        saveUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUserBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 102, 102));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtnMouseExited(evt);
            }
        });
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        vChkBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vChkBox.setText("V");
        vChkBox.setToolTipText("Add v at the end of nic");

        lNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTxtBoxActionPerformed(evt);
            }
        });

        addrTxtBox2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addrTxtBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrTxtBox2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("First Name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Address Line 01");

        fNameTxtBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fNameTxtBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTxtBox1ActionPerformed(evt);
            }
        });

        addrTxtBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addrTxtBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrTxtBox1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Email Address");

        emailTxtBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        emailTxtBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(254, 254, 254)
                .addComponent(jLabel11)
                .addGap(261, 261, 261)
                .addComponent(jLabel6))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fNameTxtBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addGap(170, 170, 170)
                .addComponent(vChkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nicTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(22, 22, 22)
                .addComponent(addrTxtBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactTxtBox01, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactTxtBox02, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addrTxtBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel13)
                .addGap(216, 216, 216)
                .addComponent(jLabel10))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(emailTxtBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(salaryTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(saveUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(updateUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fNameTxtBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(vChkBox)
                    .addComponent(jLabel12))
                .addGap(1, 1, 1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nicTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9))
                    .addComponent(addrTxtBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(contactTxtBox01, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(contactTxtBox02, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)
                        .addComponent(addrTxtBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailTxtBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 10, 950, 590));

        menuPanel.setBackground(new java.awt.Color(210, 180, 140));
        menuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(210, 180, 140));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));

        updateProfileBtn.setBackground(new java.awt.Color(255, 239, 153));
        updateProfileBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateProfileBtn.setText("Update Profile");
        updateProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseExited(evt);
            }
        });
        updateProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileBtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_customer_40px.png"))); // NOI18N

        uNameLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uNameLable.setText("Admin Name");
        uNameLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        uIDLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uIDLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uIDLable.setText("Admin Id");
        uIDLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uIDLable, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(uIDLable, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(uNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 140));

        inventoryDetailsBtn.setBackground(new java.awt.Color(64, 224, 208));
        inventoryDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        inventoryDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_trolley_24px.png"))); // NOI18N
        inventoryDetailsBtn.setText("Inventory Details");
        inventoryDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryDetailsBtnMouseExited(evt);
            }
        });
        inventoryDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(inventoryDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 300, 40));

        billTerminaBtn1.setBackground(new java.awt.Color(64, 224, 208));
        billTerminaBtn1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        billTerminaBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_bill_24px.png"))); // NOI18N
        billTerminaBtn1.setText(" Billing Terminal");
        billTerminaBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billTerminaBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billTerminaBtn1MouseExited(evt);
            }
        });
        billTerminaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billTerminaBtn1ActionPerformed(evt);
            }
        });
        menuPanel.add(billTerminaBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 300, 40));

        uDetailsBtn.setBackground(new java.awt.Color(51, 204, 255));
        uDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_user_24px.png"))); // NOI18N
        uDetailsBtn.setText("User Details");
        uDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uDetailsBtnMouseExited(evt);
            }
        });
        uDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(uDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 300, 40));

        setMenuBtn.setBackground(new java.awt.Color(64, 224, 208));
        setMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        setMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_restaurant_menu_24px.png"))); // NOI18N
        setMenuBtn.setText("Set Menu Details");
        setMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                setMenuBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                setMenuBtnMouseExited(evt);
            }
        });
        setMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMenuBtnActionPerformed(evt);
            }
        });
        menuPanel.add(setMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 300, 40));

        suppDetailsBtn.setBackground(new java.awt.Color(64, 224, 208));
        suppDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        suppDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_supplier_24px.png"))); // NOI18N
        suppDetailsBtn.setText("Supplier Details");
        suppDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suppDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppDetailsBtnMouseExited(evt);
            }
        });
        suppDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(suppDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 300, 40));

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_left_arrow_24px.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        menuPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 140, 30));

        logOutBtn.setBackground(new java.awt.Color(255, 153, 153));
        logOutBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtnMouseExited(evt);
            }
        });
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        menuPanel.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 140, 30));

        clockInBtn.setBackground(new java.awt.Color(153, 255, 153));
        clockInBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_clock_checked_24px.png"))); // NOI18N
        clockInBtn.setText(" Mark Clock in");
        clockInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockInBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockInBtnMouseExited(evt);
            }
        });
        clockInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockInBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 300, 40));

        clockOffBtn.setBackground(new java.awt.Color(255, 102, 102));
        clockOffBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockOffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_alarm_off_24px.png"))); // NOI18N
        clockOffBtn.setText(" Mark Clock off");
        clockOffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseExited(evt);
            }
        });
        clockOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockOffBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockOffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 300, 40));

        jPanel1.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseClicked
        this.setExtendedState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLableMouseClicked

    private void minimizeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseEntered
        minimizeLable.setOpaque(true);
        minimizeLable.setBackground(new Color(210, 180, 140));
        minimizeLable.repaint();
    }//GEN-LAST:event_minimizeLableMouseEntered

    private void minimizeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseExited
        minimizeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_minimizeLableMouseExited

    private void closeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseClicked
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to exit?") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeLableMouseClicked

    private void closeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseEntered
        closeLable.setOpaque(true);
        closeLable.setBackground(new Color(210, 180, 140));
        closeLable.repaint();
    }//GEN-LAST:event_closeLableMouseEntered

    private void closeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseExited
        closeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_closeLableMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;
        int x = getLocation().x + xMoved;
        int y = getLocation().y + yMoved;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanel3MousePressed

    private void userIdTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdTxtBoxActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked

    }//GEN-LAST:event_jPanel5MouseClicked

    private void nicTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicTxtBoxActionPerformed

    private void contactTxtBox01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTxtBox01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTxtBox01ActionPerformed

    private void contactTxtBox02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTxtBox02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTxtBox02ActionPerformed

    private void salaryTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryTxtBoxActionPerformed

    private void updateUserBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateUserBtnMouseEntered
        updateUserBtn.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_updateUserBtnMouseEntered

    private void updateUserBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateUserBtnMouseExited
        updateUserBtn.setBackground(new Color(204, 255, 153));
    }//GEN-LAST:event_updateUserBtnMouseExited

    private void updateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserBtnActionPerformed
        String userID = userIdTxtBox.getText();
        String fName = fNameTxtBox1.getText();
        String lName = lNameTxtBox.getText();
        String nic = nicTxtBox.getText();
        String addr1 = addrTxtBox1.getText();
        String addr2 = addrTxtBox2.getText();
        String contact1 = contactTxtBox01.getText();
        String contact2 = contactTxtBox02.getText();
        String email = emailTxtBox1.getText();
        double salary = Double.parseDouble(salaryTxtBox.getText());
        String role = userRoleTxtBox.getText();

        if (userID.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter User Id");
            userIdTxtBox.grabFocus();
        } else if (fName.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter First Name");
            fNameTxtBox1.grabFocus();
        } else if (lName.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Last Name");
            lNameTxtBox.grabFocus();
        } else if (nic.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter NIC");
            nicTxtBox.grabFocus();
        } else if (addr1.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Address Line 01");
            addrTxtBox1.grabFocus();
        } else if (addr2.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Address Line 02");
            addrTxtBox2.grabFocus();
        } else if (contact1.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Contact 1");
            contactTxtBox01.grabFocus();
        } else if (contact2.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Contact 2");
            contactTxtBox02.grabFocus();
        } else if (email.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Email");
            emailTxtBox1.grabFocus();
        } else if (salaryTxtBox.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Salary");
            salaryTxtBox.grabFocus();
        } else if (role.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter User Role");
            salaryTxtBox.grabFocus();
        } else {

            JFrame f = new JFrame();
            if (JOptionPane.showConfirmDialog(f, "Do you Want to update this user?") == JOptionPane.YES_NO_OPTION) {

                User user = new User();
                user.setId(userID);
                user.setFName(fName);
                user.setLName(lName);
                user.setNic(nic);
                user.setAddress1(addr1);
                user.setAddress2(addr2);
                user.setTele(contact1);
                user.setEmail(email);
                user.setSalary(salary);
                user.setRole(role);

                user.updateUser("admin", contact2);
                IncrementUserId();

            } else {
                JOptionPane.showMessageDialog(null, "Process Canceled");
            }

        }
    }//GEN-LAST:event_updateUserBtnActionPerformed

    private void saveUserBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveUserBtnMouseEntered
        saveUserBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_saveUserBtnMouseEntered

    private void saveUserBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveUserBtnMouseExited
        saveUserBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_saveUserBtnMouseExited

    private void saveUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUserBtnActionPerformed
        String userID = userIdTxtBox.getText();
        String fName = fNameTxtBox1.getText();
        String lName = lNameTxtBox.getText();
        String nic = nicTxtBox.getText();
        String addr1 = addrTxtBox1.getText();
        String addr2 = addrTxtBox2.getText();
        String contact1 = contactTxtBox01.getText();
        String contact2 = contactTxtBox02.getText();
        String email = emailTxtBox1.getText();
        double salary = Double.parseDouble(salaryTxtBox.getText());
        String role = userRoleTxtBox.getText();

        if (userID.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter User Id");
            userIdTxtBox.grabFocus();
        } else if (fName.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter First Name");
            fNameTxtBox1.grabFocus();
        } else if (lName.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Last Name");
            lNameTxtBox.grabFocus();
        } else if (nic.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter NIC");
            nicTxtBox.grabFocus();
        } else if (addr1.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Address Line 01");
            addrTxtBox1.grabFocus();
        } else if (addr2.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Address Line 02");
            addrTxtBox2.grabFocus();
        } else if (contact1.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Contact 1");
            contactTxtBox01.grabFocus();
        } else if (contact2.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Contact 2");
            contactTxtBox02.grabFocus();
        } else if (email.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Email");
            emailTxtBox1.grabFocus();
        } else if (salaryTxtBox.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Salary");
            salaryTxtBox.grabFocus();
        } else if (role.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter User Role");
            salaryTxtBox.grabFocus();
        } else {

            IncrementUserId();
            String password = Generator.generatePassword();
            int saltNo = Generator.generateSaltNumber();
            String hashedPwd = HashPassword.hash(password, saltNo);

            User user = new User(userID, fName, lName, nic, addr1, addr2, email, role, hashedPwd, contact1, saltNo, salary);
            user.addUser(contact2);
            Emailer.sendLoginInfo(email, fName + " " + lName, role, userID, password);

        }

    }//GEN-LAST:event_saveUserBtnActionPerformed

    private void clearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseEntered
        clearBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clearBtnMouseEntered

    private void clearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseExited
        clearBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clearBtnMouseExited

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        addrTxtBox2.setText("");
        lNameTxtBox.setText("");
        nicTxtBox.setText("");
        addrTxtBox1.setText("");
        addrTxtBox2.setText("");
        contactTxtBox01.setText("");
        contactTxtBox02.setText("");
        salaryTxtBox.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void contactTxtBox01KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactTxtBox01KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (contactTxtBox01.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_contactTxtBox01KeyTyped

    private void contactTxtBox02KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactTxtBox02KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (contactTxtBox02.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_contactTxtBox02KeyTyped

    private void nicTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTxtBoxKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (nicTxtBox.getText().trim().length() == 13) {
            evt.consume();
        }
    }//GEN-LAST:event_nicTxtBoxKeyTyped

    private void updateProfileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseEntered
        updateProfileBtn.setBackground(new Color(255, 255, 153));
    }//GEN-LAST:event_updateProfileBtnMouseEntered

    private void updateProfileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseExited
        updateProfileBtn.setBackground(new Color(255, 239, 153));
    }//GEN-LAST:event_updateProfileBtnMouseExited

    private void updateProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateProfileBtnActionPerformed

    private void inventoryDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryDetailsBtnMouseEntered
        inventoryDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_inventoryDetailsBtnMouseEntered

    private void inventoryDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryDetailsBtnMouseExited
        inventoryDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_inventoryDetailsBtnMouseExited

    private void inventoryDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryDetailsBtnActionPerformed
        this.dispose();
        new InventoryDetailsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_inventoryDetailsBtnActionPerformed

    private void billTerminaBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn1MouseEntered
        billTerminaBtn1.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_billTerminaBtn1MouseEntered

    private void billTerminaBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn1MouseExited
        billTerminaBtn1.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_billTerminaBtn1MouseExited

    private void billTerminaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billTerminaBtn1ActionPerformed
        this.dispose();
        new BillingFrame(3,uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_billTerminaBtn1ActionPerformed

    private void uDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uDetailsBtnMouseEntered
        uDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_uDetailsBtnMouseEntered

    private void uDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uDetailsBtnMouseExited
        uDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_uDetailsBtnMouseExited

    private void uDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uDetailsBtnActionPerformed
        this.dispose();
        new UserDetailsFrame(admId, admName).setVisible(true);
    }//GEN-LAST:event_uDetailsBtnActionPerformed

    private void setMenuBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMenuBtnMouseEntered
        setMenuBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_setMenuBtnMouseEntered

    private void setMenuBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMenuBtnMouseExited
        setMenuBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_setMenuBtnMouseExited

    private void setMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMenuBtnActionPerformed
        this.dispose();
        new SetMenuFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_setMenuBtnActionPerformed

    private void suppDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppDetailsBtnMouseEntered
        suppDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_suppDetailsBtnMouseEntered

    private void suppDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppDetailsBtnMouseExited
        suppDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_suppDetailsBtnMouseExited

    private void suppDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppDetailsBtnActionPerformed
        this.dispose();
        new supplierDetails(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_suppDetailsBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new UserDetailsFrame(admId, admName).setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        User user = new User();
        int result = user.logOut();
        if (result == JOptionPane.YES_NO_OPTION) {
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void lNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTxtBoxActionPerformed

    private void addrTxtBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrTxtBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrTxtBox2ActionPerformed

    private void fNameTxtBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTxtBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTxtBox1ActionPerformed

    private void addrTxtBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrTxtBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrTxtBox1ActionPerformed

    private void emailTxtBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtBox1ActionPerformed

    private void salaryTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryTxtBoxKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_salaryTxtBoxKeyTyped

    private void userRoleTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRoleTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userRoleTxtBoxActionPerformed

    private void clockInBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseEntered
        clockInBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_clockInBtnMouseEntered

    private void clockInBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseExited
        clockInBtn.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_clockInBtnMouseExited

    private void clockInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockInBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clock In?") == JOptionPane.YES_NO_OPTION) {
            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.setClockinTime(LocalTime.now());
            timeSheet.markClockin();
        }
    }//GEN-LAST:event_clockInBtnActionPerformed

    private void clockOffBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseEntered
        clockOffBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clockOffBtnMouseEntered

    private void clockOffBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseExited
        clockOffBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clockOffBtnMouseExited

    private void clockOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockOffBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clok off time") == JOptionPane.YES_NO_OPTION) {

            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());
            timeSheet.setClockoffTime(LocalTime.now());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.markClockoff();

        }
    }//GEN-LAST:event_clockOffBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUserFrame("", "", "", "", "", "", "", "", "", "", "", "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrTxtBox1;
    private javax.swing.JTextField addrTxtBox2;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton billTerminaBtn1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clockInBtn;
    private javax.swing.JButton clockOffBtn;
    private javax.swing.JLabel closeLable;
    private javax.swing.JTextField contactTxtBox01;
    private javax.swing.JTextField contactTxtBox02;
    private javax.swing.JLabel dateLable;
    private javax.swing.JTextField emailTxtBox1;
    private javax.swing.JTextField fNameTxtBox1;
    private javax.swing.JButton inventoryDetailsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField lNameTxtBox;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minimizeLable;
    private javax.swing.JTextField nicTxtBox;
    private javax.swing.JTextField salaryTxtBox;
    private javax.swing.JButton saveUserBtn;
    private javax.swing.JButton setMenuBtn;
    private javax.swing.JButton suppDetailsBtn;
    private javax.swing.JLabel timeLable;
    private javax.swing.JButton uDetailsBtn;
    private javax.swing.JLabel uIDLable;
    private javax.swing.JLabel uNameLable;
    private javax.swing.JButton updateProfileBtn;
    private javax.swing.JButton updateUserBtn;
    private javax.swing.JTextField userIdTxtBox;
    private javax.swing.JTextField userRoleTxtBox;
    private javax.swing.JCheckBox vChkBox;
    // End of variables declaration//GEN-END:variables
}
