/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import Others.*;
import Classes.*;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinis
 */
public class BranchManagerProfile extends javax.swing.JFrame {

    /**
     * Creates new form BranchManagerProfile
     */
    static Point initialClick;

    public BranchManagerProfile(String uId, String name) {
        initComponents();

        uIDLable.setText(uId);
        uNameLable.setText(name);
        
        dateLable.setText(DateTime.showDate());
        time();

    }

    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    public void loadRequests() {

        try {

            Request req = new Request();
            User user = new User();
            ResultSet rs = req.viewRequest("*", "status = ?", "BM");

            DefaultTableModel df = (DefaultTableModel) hrInfoTable.getModel();
            int rc = df.getRowCount();
            for (int i = 0; i < rc; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector();
                String uId = rs.getString("user_id");
                v.add(uId);

                ResultSet rs2 = user.viewUser("fname", "user_id = ?", uId);
                String fName = "";
                if (rs2.next()) {
                    fName = rs2.getString("fname");
                }

                v.add(fName);
                v.add(rs.getString("description"));
                v.add(rs.getString("status"));
                v.add(rs.getString("req_id"));
                df.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void hideRIdColumn() {

        hrInfoTable.getColumnModel().getColumn(4).setMinWidth(0);
        hrInfoTable.getColumnModel().getColumn(4).setMaxWidth(0);
        hrInfoTable.getColumnModel().getColumn(4).setWidth(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        minimizeLable = new javax.swing.JLabel();
        closeLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uNameLable = new javax.swing.JLabel();
        uIDLable = new javax.swing.JLabel();
        updateProfileBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        clockOffBtn = new javax.swing.JButton();
        clockInBtn = new javax.swing.JButton();
        assignTaskBtn = new javax.swing.JButton();
        bulkOrderBtn = new javax.swing.JButton();
        productDetailsBtn = new javax.swing.JButton();
        billTerminaBtn2 = new javax.swing.JButton();
        sendNoteBtn = new javax.swing.JButton();
        empDetailsBtn = new javax.swing.JButton();
        viewLogBtn = new javax.swing.JButton();
        markExpencessBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        hrInfoTable = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        adminInfoTable = new javax.swing.JTable();
        approveBtn = new javax.swing.JButton();
        denyBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        discountRateTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        taxRateTable = new javax.swing.JTable();
        taxRateTxtBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        discountRateTxtBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        productTxtBox = new javax.swing.JTextField();
        saveTaxBtn = new javax.swing.JButton();
        updateTaxBtn = new javax.swing.JButton();
        clearTaxBtn = new javax.swing.JButton();
        saveDiscBtn = new javax.swing.JButton();
        updateDiscBtn = new javax.swing.JButton();
        clearDiscBtn = new javax.swing.JButton();
        allowTaxBtn = new javax.swing.JButton();
        allowDiscBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 222, 179));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_16px.png"))); // NOI18N
        minimizeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLableMouseExited(evt);
            }
        });
        jPanel3.add(minimizeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 1, 30, 28));

        closeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_16px.png"))); // NOI18N
        closeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLableMouseExited(evt);
            }
        });
        jPanel3.add(closeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1259, 1, 30, 28));

        timeLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 150, 30));

        dateLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        jPanel1.setBackground(new java.awt.Color(242, 224, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(210, 180, 140));
        menuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(210, 180, 140));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_businessman_40px.png"))); // NOI18N

        uNameLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uNameLable.setText("Branch Manager Name");
        uNameLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        uIDLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uIDLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uIDLable.setText("Branch Manager Id");
        uIDLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        updateProfileBtn.setBackground(new java.awt.Color(255, 239, 153));
        updateProfileBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateProfileBtn.setText("Update Profile");
        updateProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseExited(evt);
            }
        });
        updateProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uIDLable, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(updateProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(uIDLable, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(uNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 140));

        logOutBtn.setBackground(new java.awt.Color(255, 153, 153));
        logOutBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtnMouseExited(evt);
            }
        });
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        menuPanel.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 250, 20));

        clockOffBtn.setBackground(new java.awt.Color(255, 102, 102));
        clockOffBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockOffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_alarm_off_24px.png"))); // NOI18N
        clockOffBtn.setText(" Mark Clock off");
        clockOffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseExited(evt);
            }
        });
        clockOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockOffBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockOffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 300, 30));

        clockInBtn.setBackground(new java.awt.Color(153, 255, 153));
        clockInBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_clock_checked_24px.png"))); // NOI18N
        clockInBtn.setText(" Mark Clock in");
        clockInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockInBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockInBtnMouseExited(evt);
            }
        });
        clockInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockInBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 300, 30));

        assignTaskBtn.setBackground(new java.awt.Color(64, 224, 208));
        assignTaskBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        assignTaskBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_task_24px.png"))); // NOI18N
        assignTaskBtn.setText(" Assign Tasks");
        assignTaskBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                assignTaskBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                assignTaskBtnMouseExited(evt);
            }
        });
        assignTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignTaskBtnActionPerformed(evt);
            }
        });
        menuPanel.add(assignTaskBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 300, 30));

        bulkOrderBtn.setBackground(new java.awt.Color(64, 224, 208));
        bulkOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bulkOrderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_purchase_order_24px.png"))); // NOI18N
        bulkOrderBtn.setText(" Bulk Order Details");
        bulkOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bulkOrderBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bulkOrderBtnMouseExited(evt);
            }
        });
        bulkOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulkOrderBtnActionPerformed(evt);
            }
        });
        menuPanel.add(bulkOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 300, 30));

        productDetailsBtn.setBackground(new java.awt.Color(64, 224, 208));
        productDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        productDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_box_24px.png"))); // NOI18N
        productDetailsBtn.setText(" Products Details");
        productDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productDetailsBtnMouseExited(evt);
            }
        });
        productDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(productDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 300, 30));

        billTerminaBtn2.setBackground(new java.awt.Color(64, 224, 208));
        billTerminaBtn2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        billTerminaBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_bill_24px.png"))); // NOI18N
        billTerminaBtn2.setText(" Billing Terminal");
        billTerminaBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billTerminaBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billTerminaBtn2MouseExited(evt);
            }
        });
        billTerminaBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billTerminaBtn2ActionPerformed(evt);
            }
        });
        menuPanel.add(billTerminaBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 300, 30));

        sendNoteBtn.setBackground(new java.awt.Color(64, 224, 208));
        sendNoteBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        sendNoteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_notification_24px.png"))); // NOI18N
        sendNoteBtn.setText(" Send Notifications");
        sendNoteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendNoteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendNoteBtnMouseExited(evt);
            }
        });
        sendNoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendNoteBtnActionPerformed(evt);
            }
        });
        menuPanel.add(sendNoteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 300, 30));

        empDetailsBtn.setBackground(new java.awt.Color(64, 224, 208));
        empDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        empDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_employee_24px.png"))); // NOI18N
        empDetailsBtn.setText("Employee Details");
        empDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empDetailsBtnMouseExited(evt);
            }
        });
        empDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(empDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 300, 30));

        viewLogBtn.setBackground(new java.awt.Color(64, 224, 208));
        viewLogBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        viewLogBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_logs_folder_24px.png"))); // NOI18N
        viewLogBtn.setText(" View Log Sheets");
        viewLogBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewLogBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewLogBtnMouseExited(evt);
            }
        });
        viewLogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLogBtnActionPerformed(evt);
            }
        });
        menuPanel.add(viewLogBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 300, 30));

        markExpencessBtn.setBackground(new java.awt.Color(64, 224, 208));
        markExpencessBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        markExpencessBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_expensive_price_24px.png"))); // NOI18N
        markExpencessBtn.setText(" Mark Expencess");
        markExpencessBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                markExpencessBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                markExpencessBtnMouseExited(evt);
            }
        });
        markExpencessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markExpencessBtnActionPerformed(evt);
            }
        });
        menuPanel.add(markExpencessBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 300, 30));

        jPanel1.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 590));

        jPanel4.setBackground(new java.awt.Color(245, 222, 179));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Admin Infroms");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HR Infroms");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        hrInfoTable.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        hrInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User Id", "Name", "Description", "Made Date", "Id"
            }
        ));
        jScrollPane4.setViewportView(hrInfoTable);

        adminInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Reason", "Description"
            }
        ));
        jScrollPane7.setViewportView(adminInfoTable);

        approveBtn.setBackground(new java.awt.Color(102, 255, 102));
        approveBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        approveBtn.setText("Approve");
        approveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                approveBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                approveBtnMouseExited(evt);
            }
        });
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        denyBtn.setBackground(new java.awt.Color(255, 102, 102));
        denyBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        denyBtn.setText("Deny");
        denyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                denyBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                denyBtnMouseExited(evt);
            }
        });
        denyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(denyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(denyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 550, 590));

        jPanel5.setBackground(new java.awt.Color(245, 222, 179));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pricing Rate Details");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        discountRateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Discount Rate", "Product"
            }
        ));
        jScrollPane5.setViewportView(discountRateTable);

        taxRateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tax Rate"
            }
        ));
        jScrollPane6.setViewportView(taxRateTable);

        taxRateTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        taxRateTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxRateTxtBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Tax Rate");

        discountRateTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        discountRateTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountRateTxtBoxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Discount Rate");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Product");

        productTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        productTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTxtBoxActionPerformed(evt);
            }
        });

        saveTaxBtn.setBackground(new java.awt.Color(102, 255, 102));
        saveTaxBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveTaxBtn.setText("Save");
        saveTaxBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveTaxBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveTaxBtnMouseExited(evt);
            }
        });

        updateTaxBtn.setBackground(new java.awt.Color(204, 255, 153));
        updateTaxBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateTaxBtn.setText("Update");
        updateTaxBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateTaxBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateTaxBtnMouseExited(evt);
            }
        });
        updateTaxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTaxBtnActionPerformed(evt);
            }
        });

        clearTaxBtn.setBackground(new java.awt.Color(255, 102, 102));
        clearTaxBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearTaxBtn.setText("Clear");
        clearTaxBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearTaxBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearTaxBtnMouseExited(evt);
            }
        });
        clearTaxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTaxBtnActionPerformed(evt);
            }
        });

        saveDiscBtn.setBackground(new java.awt.Color(102, 255, 102));
        saveDiscBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveDiscBtn.setText("Save");
        saveDiscBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveDiscBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveDiscBtnMouseExited(evt);
            }
        });

        updateDiscBtn.setBackground(new java.awt.Color(204, 255, 153));
        updateDiscBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateDiscBtn.setText("Update");
        updateDiscBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateDiscBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateDiscBtnMouseExited(evt);
            }
        });
        updateDiscBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDiscBtnActionPerformed(evt);
            }
        });

        clearDiscBtn.setBackground(new java.awt.Color(255, 102, 102));
        clearDiscBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearDiscBtn.setText("Clear");
        clearDiscBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearDiscBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearDiscBtnMouseExited(evt);
            }
        });
        clearDiscBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDiscBtnActionPerformed(evt);
            }
        });

        allowTaxBtn.setBackground(new java.awt.Color(153, 255, 51));
        allowTaxBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        allowTaxBtn.setText("Allow");
        allowTaxBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                allowTaxBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                allowTaxBtnMouseExited(evt);
            }
        });

        allowDiscBtn.setBackground(new java.awt.Color(153, 255, 51));
        allowDiscBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        allowDiscBtn.setText("Allow");
        allowDiscBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                allowDiscBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                allowDiscBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(taxRateTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateTaxBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saveTaxBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(clearTaxBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(allowTaxBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(discountRateTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateDiscBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saveDiscBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allowDiscBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearDiscBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(212, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(taxRateTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveTaxBtn)
                            .addComponent(allowTaxBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateTaxBtn)
                            .addComponent(clearTaxBtn))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discountRateTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveDiscBtn)
                            .addComponent(allowDiscBtn))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateDiscBtn)
                            .addComponent(clearDiscBtn))))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(455, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 10, 390, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseClicked
        this.setExtendedState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLableMouseClicked

    private void minimizeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseEntered
        minimizeLable.setOpaque(true);
        minimizeLable.setBackground(new Color(210, 180, 140));
        minimizeLable.repaint();
    }//GEN-LAST:event_minimizeLableMouseEntered

    private void minimizeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseExited
        minimizeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_minimizeLableMouseExited

    private void closeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseClicked
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to exit?") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeLableMouseClicked

    private void closeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseEntered
        closeLable.setOpaque(true);
        closeLable.setBackground(new Color(210, 180, 140));
        closeLable.repaint();
    }//GEN-LAST:event_closeLableMouseEntered

    private void closeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseExited
        closeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_closeLableMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;
        int x = getLocation().x + xMoved;
        int y = getLocation().y + yMoved;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanel3MousePressed

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        User user = new User();
        int result = user.logOut();
        if (result == JOptionPane.YES_NO_OPTION) {
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void clockOffBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseEntered
        clockOffBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clockOffBtnMouseEntered

    private void clockOffBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseExited
        clockOffBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clockOffBtnMouseExited

    private void clockOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockOffBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clok off time") == JOptionPane.YES_NO_OPTION) {

            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());
            timeSheet.setClockoffTime(LocalTime.now());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.markClockoff();

        }
    }//GEN-LAST:event_clockOffBtnActionPerformed

    private void clockInBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseEntered
        clockInBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_clockInBtnMouseEntered

    private void clockInBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseExited
        clockInBtn.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_clockInBtnMouseExited

    private void clockInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockInBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clok off time") == JOptionPane.YES_NO_OPTION) {

            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());
            timeSheet.setClockoffTime(LocalTime.now());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.markClockoff();

        }
    }//GEN-LAST:event_clockInBtnActionPerformed

    private void assignTaskBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignTaskBtnMouseEntered
        assignTaskBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_assignTaskBtnMouseEntered

    private void assignTaskBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignTaskBtnMouseExited
        assignTaskBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_assignTaskBtnMouseExited

    private void assignTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignTaskBtnActionPerformed
        this.dispose();
        new BmAssignTaskFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_assignTaskBtnActionPerformed

    private void bulkOrderBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bulkOrderBtnMouseEntered
        bulkOrderBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_bulkOrderBtnMouseEntered

    private void bulkOrderBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bulkOrderBtnMouseExited
        bulkOrderBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_bulkOrderBtnMouseExited

    private void bulkOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulkOrderBtnActionPerformed
        this.dispose();
        new BulkOrderDetailsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_bulkOrderBtnActionPerformed

    private void productDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productDetailsBtnMouseEntered
        productDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_productDetailsBtnMouseEntered

    private void productDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productDetailsBtnMouseExited
        productDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_productDetailsBtnMouseExited

    private void productDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productDetailsBtnActionPerformed
        this.dispose();
        new ProductDetailsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_productDetailsBtnActionPerformed

    private void billTerminaBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn2MouseEntered
        billTerminaBtn2.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_billTerminaBtn2MouseEntered

    private void billTerminaBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn2MouseExited
        billTerminaBtn2.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_billTerminaBtn2MouseExited

    private void billTerminaBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billTerminaBtn2ActionPerformed
        this.dispose();
        new BillingFrame(8,uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_billTerminaBtn2ActionPerformed

    private void sendNoteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendNoteBtnMouseEntered
        sendNoteBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_sendNoteBtnMouseEntered

    private void sendNoteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendNoteBtnMouseExited
        sendNoteBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_sendNoteBtnMouseExited

    private void sendNoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendNoteBtnActionPerformed
        this.dispose();
        new SendNotificationsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_sendNoteBtnActionPerformed

    private void taxRateTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxRateTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxRateTxtBoxActionPerformed

    private void discountRateTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountRateTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountRateTxtBoxActionPerformed

    private void productTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productTxtBoxActionPerformed

    private void saveTaxBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTaxBtnMouseEntered
        saveTaxBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_saveTaxBtnMouseEntered

    private void saveTaxBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTaxBtnMouseExited
        saveTaxBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_saveTaxBtnMouseExited

    private void updateTaxBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTaxBtnMouseEntered
        updateTaxBtn.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_updateTaxBtnMouseEntered

    private void updateTaxBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTaxBtnMouseExited
        updateTaxBtn.setBackground(new Color(204, 255, 153));
    }//GEN-LAST:event_updateTaxBtnMouseExited

    private void updateTaxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTaxBtnActionPerformed

    }//GEN-LAST:event_updateTaxBtnActionPerformed

    private void clearTaxBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearTaxBtnMouseEntered
        clearTaxBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clearTaxBtnMouseEntered

    private void clearTaxBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearTaxBtnMouseExited
        clearTaxBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clearTaxBtnMouseExited

    private void clearTaxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTaxBtnActionPerformed
        taxRateTxtBox.setText("");
    }//GEN-LAST:event_clearTaxBtnActionPerformed

    private void saveDiscBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveDiscBtnMouseEntered
        saveDiscBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_saveDiscBtnMouseEntered

    private void saveDiscBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveDiscBtnMouseExited
        saveDiscBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_saveDiscBtnMouseExited

    private void updateDiscBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateDiscBtnMouseEntered
        updateDiscBtn.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_updateDiscBtnMouseEntered

    private void updateDiscBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateDiscBtnMouseExited
        updateDiscBtn.setBackground(new Color(204, 255, 153));
    }//GEN-LAST:event_updateDiscBtnMouseExited

    private void updateDiscBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDiscBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateDiscBtnActionPerformed

    private void clearDiscBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearDiscBtnMouseEntered
        clearDiscBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clearDiscBtnMouseEntered

    private void clearDiscBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearDiscBtnMouseExited
        clearDiscBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clearDiscBtnMouseExited

    private void clearDiscBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDiscBtnActionPerformed
        discountRateTxtBox.setText("");
        productTxtBox.setText("");
    }//GEN-LAST:event_clearDiscBtnActionPerformed

    private void empDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empDetailsBtnMouseEntered
        empDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_empDetailsBtnMouseEntered

    private void empDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empDetailsBtnMouseExited
        empDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_empDetailsBtnMouseExited

    private void empDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empDetailsBtnActionPerformed
        this.dispose();
        new EmpDetailsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_empDetailsBtnActionPerformed

    private void viewLogBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewLogBtnMouseEntered
        viewLogBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_viewLogBtnMouseEntered

    private void viewLogBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewLogBtnMouseExited
        viewLogBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_viewLogBtnMouseExited

    private void viewLogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLogBtnActionPerformed
        this.dispose();
        new ViewLogSheets(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_viewLogBtnActionPerformed

    private void allowTaxBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allowTaxBtnMouseEntered
        allowTaxBtn.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_allowTaxBtnMouseEntered

    private void allowTaxBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allowTaxBtnMouseExited
        allowTaxBtn.setBackground(new Color(153, 255, 51));
    }//GEN-LAST:event_allowTaxBtnMouseExited

    private void allowDiscBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allowDiscBtnMouseEntered
        allowDiscBtn.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_allowDiscBtnMouseEntered

    private void allowDiscBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allowDiscBtnMouseExited
        allowDiscBtn.setBackground(new Color(153, 255, 51));
    }//GEN-LAST:event_allowDiscBtnMouseExited

    private void markExpencessBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_markExpencessBtnMouseEntered
        markExpencessBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_markExpencessBtnMouseEntered

    private void markExpencessBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_markExpencessBtnMouseExited
        markExpencessBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_markExpencessBtnMouseExited

    private void markExpencessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markExpencessBtnActionPerformed
        this.dispose();
        new BMExpenceFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_markExpencessBtnActionPerformed

    private void approveBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approveBtnMouseEntered
        approveBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_approveBtnMouseEntered

    private void approveBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approveBtnMouseExited
        approveBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_approveBtnMouseExited

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        DefaultTableModel df = (DefaultTableModel) hrInfoTable.getModel();

        if (hrInfoTable.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Select at least one Request to approve");
        } else {
            JFrame f = new JFrame();
            if (JOptionPane.showConfirmDialog(f, "Do you want to perform this action") == JOptionPane.YES_NO_OPTION) {
                int[] selectedRows = hrInfoTable.getSelectedRows();

                Request req = new Request();

                for (int row : selectedRows) {
                    int modelRow = hrInfoTable.convertRowIndexToModel(row);
                    req.setReqId(Integer.parseInt(df.getValueAt(modelRow, 4).toString()));
                    req.setStatus("Approved");
                    req.approveRequest();
                }
                loadRequests();
            }
        }
    }//GEN-LAST:event_approveBtnActionPerformed

    private void denyBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_denyBtnMouseEntered
        denyBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_denyBtnMouseEntered

    private void denyBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_denyBtnMouseExited
        denyBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_denyBtnMouseExited

    private void denyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyBtnActionPerformed
        DefaultTableModel df = (DefaultTableModel) hrInfoTable.getModel();

        if (hrInfoTable.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Select at least one Request to approve");
        } else {
            JFrame f = new JFrame();
            if (JOptionPane.showConfirmDialog(f, "Do you want to perform this action") == JOptionPane.YES_NO_OPTION) {
                int[] selectedRows = hrInfoTable.getSelectedRows();

                Request req = new Request();

                for (int row : selectedRows) {
                    int modelRow = hrInfoTable.convertRowIndexToModel(row);
                    req.setReqId(Integer.parseInt(df.getValueAt(modelRow, 4).toString()));
                    req.setStatus("Denied");
                    req.denyRequest();
                }
                loadRequests();
            }
        }
    }//GEN-LAST:event_denyBtnActionPerformed

    private void updateProfileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseEntered
        updateProfileBtn.setBackground(new Color(255, 255, 153));
    }//GEN-LAST:event_updateProfileBtnMouseEntered

    private void updateProfileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseExited
        updateProfileBtn.setBackground(new Color(255, 239, 153));
    }//GEN-LAST:event_updateProfileBtnMouseExited

    private void updateProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileBtnActionPerformed
        this.dispose();
        new UpdateProfileFrame(8,uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_updateProfileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchManagerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchManagerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchManagerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchManagerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BranchManagerProfile("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminInfoTable;
    private javax.swing.JButton allowDiscBtn;
    private javax.swing.JButton allowTaxBtn;
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton assignTaskBtn;
    private javax.swing.JButton billTerminaBtn2;
    private javax.swing.JButton bulkOrderBtn;
    private javax.swing.JButton clearDiscBtn;
    private javax.swing.JButton clearTaxBtn;
    private javax.swing.JButton clockInBtn;
    private javax.swing.JButton clockOffBtn;
    private javax.swing.JLabel closeLable;
    private javax.swing.JLabel dateLable;
    private javax.swing.JButton denyBtn;
    private javax.swing.JTable discountRateTable;
    private javax.swing.JTextField discountRateTxtBox;
    private javax.swing.JButton empDetailsBtn;
    private javax.swing.JTable hrInfoTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton markExpencessBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minimizeLable;
    private javax.swing.JButton productDetailsBtn;
    private javax.swing.JTextField productTxtBox;
    private javax.swing.JButton saveDiscBtn;
    private javax.swing.JButton saveTaxBtn;
    private javax.swing.JButton sendNoteBtn;
    private javax.swing.JTable taxRateTable;
    private javax.swing.JTextField taxRateTxtBox;
    private javax.swing.JLabel timeLable;
    private javax.swing.JLabel uIDLable;
    private javax.swing.JLabel uNameLable;
    private javax.swing.JButton updateDiscBtn;
    private javax.swing.JButton updateProfileBtn;
    private javax.swing.JButton updateTaxBtn;
    private javax.swing.JButton viewLogBtn;
    // End of variables declaration//GEN-END:variables
}
