/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import Others.*;
import Classes.*;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinis
 */
public class InventoryDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form InventoryDetailsFrame
     */
    static Point initialClick;

    int itmId = 0;

    public InventoryDetailsFrame(String uid, String name) {
        initComponents();

        uIDLable.setText(uid);
        uNameLable.setText(name);

        dateLable.setText(DateTime.showDate());
        time();
        loadItem();
        setId();
        adjustTbColums();
    }

    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    public void loadItem() {

        try {

            InventoryItem item = new InventoryItem();
            ResultSet rs = item.viewInvenory("*", "");

            DefaultTableModel df = (DefaultTableModel) inventoryTable.getModel();
            int rc = df.getRowCount();
            for (int i = 0; i < rc; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("item_id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("type"));
                v.add(rs.getString("price"));
                v.add(rs.getString("quantity"));
                v.add(rs.getString("unit"));
                df.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void setId() {

        DefaultTableModel df = (DefaultTableModel) inventoryTable.getModel();
        int rc = df.getRowCount();

        if (rc > 0) {

            int lastRowIndex = rc - 1;
            int cc = df.getColumnCount();
            for (int ci = 0; ci < cc; ci++) {
                Object val = df.getValueAt(lastRowIndex, ci);
            }

            int id = Integer.parseInt(df.getValueAt(lastRowIndex, 0).toString());
            id += 1;
            inventoryIDTxtBox.setText(id + "");
            inventoryIDTxtBox.disable();

        }

    }

    private void adjustTbColums() {

        inventoryTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        inventoryTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        inventoryTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        inventoryTable.getColumnModel().getColumn(3).setPreferredWidth(70);
        inventoryTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        inventoryTable.getColumnModel().getColumn(5).setPreferredWidth(50);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        minimizeLable = new javax.swing.JLabel();
        closeLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inventoryIDTxtBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inventoryNameTxtBox = new javax.swing.JTextField();
        itemTypeCmbBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        qtySpinner = new com.toedter.components.JSpinField();
        jLabel10 = new javax.swing.JLabel();
        saveInventoryBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        updateInventoryBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        priceTxtBox = new javax.swing.JTextField();
        pcsRBtn = new javax.swing.JRadioButton();
        kgRBtn = new javax.swing.JRadioButton();
        lRBtn = new javax.swing.JRadioButton();
        mlRBtn = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        itemIDTxtBox = new javax.swing.JTextField();
        searchByIdBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        deleteItemBtn = new javax.swing.JButton();
        itemNameTxtBox = new javax.swing.JTextField();
        searchNameBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        stockDetailsBtn = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        updateProfileBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uNameLable = new javax.swing.JLabel();
        uIDLable = new javax.swing.JLabel();
        inventoryDetailsBtn = new javax.swing.JButton();
        billTerminaBtn1 = new javax.swing.JButton();
        uDetailsBtn = new javax.swing.JButton();
        setMenuBtn = new javax.swing.JButton();
        suppDetailsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        clockInBtn = new javax.swing.JButton();
        clockOffBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 222, 179));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_16px.png"))); // NOI18N
        minimizeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLableMouseExited(evt);
            }
        });
        jPanel3.add(minimizeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 1, 30, 28));

        closeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_16px.png"))); // NOI18N
        closeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLableMouseExited(evt);
            }
        });
        jPanel3.add(closeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1259, 1, 30, 28));

        timeLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 150, 30));

        dateLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        jPanel1.setBackground(new java.awt.Color(242, 224, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(245, 222, 179));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add / Edit Inventory");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        inventoryIDTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        inventoryIDTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryIDTxtBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Inventory Item Id");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Inventory Item Name");

        inventoryNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        inventoryNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryNameTxtBoxActionPerformed(evt);
            }
        });

        itemTypeCmbBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        itemTypeCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingredient", "Non-Ingredient" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Item Type");

        qtySpinner.setToolTipText("");
        qtySpinner.setMinimum(0);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Item Quantity");

        saveInventoryBtn.setBackground(new java.awt.Color(102, 255, 102));
        saveInventoryBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveInventoryBtn.setText("Save Inventory");
        saveInventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveInventoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveInventoryBtnMouseExited(evt);
            }
        });
        saveInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveInventoryBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 102, 102));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtnMouseExited(evt);
            }
        });
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        updateInventoryBtn.setBackground(new java.awt.Color(204, 255, 153));
        updateInventoryBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateInventoryBtn.setText("Update Inventory");
        updateInventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateInventoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateInventoryBtnMouseExited(evt);
            }
        });
        updateInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInventoryBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Price");

        priceTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        priceTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtBoxActionPerformed(evt);
            }
        });
        priceTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceTxtBoxKeyTyped(evt);
            }
        });

        buttonGroup1.add(pcsRBtn);
        pcsRBtn.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        pcsRBtn.setText("PCS");

        buttonGroup1.add(kgRBtn);
        kgRBtn.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        kgRBtn.setText("Kg");

        buttonGroup1.add(lRBtn);
        lRBtn.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lRBtn.setText("L");

        buttonGroup1.add(mlRBtn);
        mlRBtn.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        mlRBtn.setText("ml");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clearBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateInventoryBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(saveInventoryBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(priceTxtBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemTypeCmbBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inventoryNameTxtBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inventoryIDTxtBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(qtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pcsRBtn)
                                    .addComponent(mlRBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lRBtn)
                                    .addComponent(kgRBtn))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryIDTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemTypeCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(3, 3, 3)
                .addComponent(priceTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pcsRBtn)
                            .addComponent(kgRBtn))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lRBtn)
                            .addComponent(mlRBtn)))
                    .addComponent(qtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 280, 590));

        jPanel5.setBackground(new java.awt.Color(245, 222, 179));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inventory Details");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        itemIDTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        itemIDTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIDTxtBoxActionPerformed(evt);
            }
        });

        searchByIdBtn.setBackground(new java.awt.Color(102, 255, 102));
        searchByIdBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchByIdBtn.setText("Search");
        searchByIdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchByIdBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchByIdBtnMouseExited(evt);
            }
        });
        searchByIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByIdBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Inventory Id");

        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Item Name", "Item Type", "Price", "Quantity", "Unit"
            }
        ));
        inventoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryTableMouseClicked(evt);
            }
        });
        inventoryTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inventoryTableKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(inventoryTable);

        deleteItemBtn.setBackground(new java.awt.Color(255, 102, 102));
        deleteItemBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteItemBtn.setText("Delete");
        deleteItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteItemBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteItemBtnMouseExited(evt);
            }
        });
        deleteItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemBtnActionPerformed(evt);
            }
        });

        itemNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        itemNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameTxtBoxActionPerformed(evt);
            }
        });

        searchNameBtn.setBackground(new java.awt.Color(102, 255, 102));
        searchNameBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchNameBtn.setText("Search");
        searchNameBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchNameBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchNameBtnMouseExited(evt);
            }
        });
        searchNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Inventory Name");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        stockDetailsBtn.setBackground(new java.awt.Color(64, 224, 208));
        stockDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        stockDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_livestock_24px.png"))); // NOI18N
        stockDetailsBtn.setText(" Stock Details");
        stockDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stockDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stockDetailsBtnMouseExited(evt);
            }
        });
        stockDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockDetailsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addComponent(deleteItemBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(searchByIdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(itemIDTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemNameTxtBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(searchNameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator2)
                    .addComponent(stockDetailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemIDTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByIdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchNameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteItemBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 10, 660, 590));

        menuPanel.setBackground(new java.awt.Color(210, 180, 140));
        menuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(210, 180, 140));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));

        updateProfileBtn.setBackground(new java.awt.Color(255, 239, 153));
        updateProfileBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateProfileBtn.setText("Update Profile");
        updateProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseExited(evt);
            }
        });
        updateProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileBtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_customer_40px.png"))); // NOI18N

        uNameLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uNameLable.setText("Admin Name");
        uNameLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        uIDLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uIDLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uIDLable.setText("Admin Id");
        uIDLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uIDLable, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(uIDLable, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(uNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 140));

        inventoryDetailsBtn.setBackground(new java.awt.Color(51, 204, 255));
        inventoryDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        inventoryDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_trolley_24px.png"))); // NOI18N
        inventoryDetailsBtn.setText("Inventory Details");
        inventoryDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryDetailsBtnMouseExited(evt);
            }
        });
        inventoryDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(inventoryDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 300, 40));

        billTerminaBtn1.setBackground(new java.awt.Color(64, 224, 208));
        billTerminaBtn1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        billTerminaBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_bill_24px.png"))); // NOI18N
        billTerminaBtn1.setText(" Billing Terminal");
        billTerminaBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billTerminaBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billTerminaBtn1MouseExited(evt);
            }
        });
        billTerminaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billTerminaBtn1ActionPerformed(evt);
            }
        });
        menuPanel.add(billTerminaBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 300, 40));

        uDetailsBtn.setBackground(new java.awt.Color(64, 224, 208));
        uDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_user_24px.png"))); // NOI18N
        uDetailsBtn.setText("User Details");
        uDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uDetailsBtnMouseExited(evt);
            }
        });
        uDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(uDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 300, 40));

        setMenuBtn.setBackground(new java.awt.Color(64, 224, 208));
        setMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        setMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_restaurant_menu_24px.png"))); // NOI18N
        setMenuBtn.setText("Set Menu Details");
        setMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                setMenuBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                setMenuBtnMouseExited(evt);
            }
        });
        setMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMenuBtnActionPerformed(evt);
            }
        });
        menuPanel.add(setMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 300, 40));

        suppDetailsBtn.setBackground(new java.awt.Color(64, 224, 208));
        suppDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        suppDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_supplier_24px.png"))); // NOI18N
        suppDetailsBtn.setText("Supplier Details");
        suppDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suppDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppDetailsBtnMouseExited(evt);
            }
        });
        suppDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(suppDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 300, 40));

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_left_arrow_24px.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        menuPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 140, 30));

        logOutBtn.setBackground(new java.awt.Color(255, 153, 153));
        logOutBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtnMouseExited(evt);
            }
        });
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        menuPanel.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 140, 30));

        clockInBtn.setBackground(new java.awt.Color(153, 255, 153));
        clockInBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_clock_checked_24px.png"))); // NOI18N
        clockInBtn.setText(" Mark Clock in");
        clockInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockInBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockInBtnMouseExited(evt);
            }
        });
        clockInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockInBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 300, 40));

        clockOffBtn.setBackground(new java.awt.Color(255, 102, 102));
        clockOffBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockOffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_alarm_off_24px.png"))); // NOI18N
        clockOffBtn.setText(" Mark Clock off");
        clockOffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseExited(evt);
            }
        });
        clockOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockOffBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockOffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 300, 40));

        jPanel1.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseClicked
        this.setExtendedState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLableMouseClicked

    private void minimizeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseEntered
        minimizeLable.setOpaque(true);
        minimizeLable.setBackground(new Color(210, 180, 140));
        minimizeLable.repaint();
    }//GEN-LAST:event_minimizeLableMouseEntered

    private void minimizeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseExited
        minimizeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_minimizeLableMouseExited

    private void closeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseClicked
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to exit?") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeLableMouseClicked

    private void closeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseEntered
        closeLable.setOpaque(true);
        closeLable.setBackground(new Color(210, 180, 140));
        closeLable.repaint();
    }//GEN-LAST:event_closeLableMouseEntered

    private void closeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseExited
        closeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_closeLableMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;
        int x = getLocation().x + xMoved;
        int y = getLocation().y + yMoved;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanel3MousePressed

    private void inventoryIDTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryIDTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryIDTxtBoxActionPerformed

    private void itemIDTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIDTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIDTxtBoxActionPerformed

    private void searchByIdBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByIdBtnMouseEntered
        searchByIdBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_searchByIdBtnMouseEntered

    private void searchByIdBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByIdBtnMouseExited
        searchByIdBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_searchByIdBtnMouseExited

    private void searchByIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByIdBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByIdBtnActionPerformed

    private void deleteItemBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteItemBtnMouseEntered
        deleteItemBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_deleteItemBtnMouseEntered

    private void deleteItemBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteItemBtnMouseExited
        deleteItemBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_deleteItemBtnMouseExited

    private void deleteItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemBtnActionPerformed
        if (itmId == 0) {
            JOptionPane.showMessageDialog(null, "Please Select an item to Delete");
        } else {

            JFrame f = new JFrame();
            if (JOptionPane.showConfirmDialog(f, "Do you want to delete this Item?") == JOptionPane.YES_NO_OPTION) {

                InventoryItem item = new InventoryItem();
                item.setItemId(itmId);
                item.removeItem();
                loadItem();

                setId();

            }

        }
    }//GEN-LAST:event_deleteItemBtnActionPerformed

    private void itemNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTxtBoxActionPerformed

    private void searchNameBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchNameBtnMouseEntered
        searchNameBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_searchNameBtnMouseEntered

    private void searchNameBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchNameBtnMouseExited
        searchNameBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_searchNameBtnMouseExited

    private void searchNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNameBtnActionPerformed

    private void inventoryNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryNameTxtBoxActionPerformed

    private void saveInventoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveInventoryBtnMouseEntered
        saveInventoryBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_saveInventoryBtnMouseEntered

    private void saveInventoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveInventoryBtnMouseExited
        saveInventoryBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_saveInventoryBtnMouseExited

    private void clearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseEntered
        clearBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clearBtnMouseEntered

    private void clearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseExited
        clearBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clearBtnMouseExited

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        inventoryNameTxtBox.setText("");
        qtySpinner.setValue(0);
        priceTxtBox.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void updateInventoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateInventoryBtnMouseEntered
        updateInventoryBtn.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_updateInventoryBtnMouseEntered

    private void updateInventoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateInventoryBtnMouseExited
        updateInventoryBtn.setBackground(new Color(204, 255, 153));
    }//GEN-LAST:event_updateInventoryBtnMouseExited

    private void updateInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInventoryBtnActionPerformed
        String itmName = inventoryNameTxtBox.getText();
        String itmType = itemTypeCmbBox.getSelectedItem().toString();
        String price = priceTxtBox.getText();
        int qty = qtySpinner.getValue();

        String unit = "";
        if (pcsRBtn.isSelected()) {
            unit = "pcs";
        } else if (kgRBtn.isSelected()) {
            unit = "kg";
        } else if (mlRBtn.isSelected()) {
            unit = "ml";
        } else if (lRBtn.isSelected()) {
            unit = "L";
        }

        if (itmId == 0) {
            JOptionPane.showMessageDialog(null, "Cannot perform this action");
        } else {

            if (itmName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter item name");
                inventoryNameTxtBox.grabFocus();
            } else if (price.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter item name");
                priceTxtBox.grabFocus();
            } else if (qty == 0) {
                JOptionPane.showMessageDialog(null, "Select a quantity");
            } else if (buttonGroup1.getSelection() == null) {
                JOptionPane.showMessageDialog(null, "Select a Unit");
            } else {

                JFrame f = new JFrame();
                if (JOptionPane.showConfirmDialog(f, "Are all the details correct") == JOptionPane.YES_NO_OPTION) {

                    InventoryItem item = new InventoryItem(itmName, itmType, Double.parseDouble(price), qty, unit);
                    item.setItemId(itmId);
                    item.updateItem();
                    loadItem();
                    setId();

                }

            }

        }
    }//GEN-LAST:event_updateInventoryBtnActionPerformed

    private void updateProfileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseEntered
        updateProfileBtn.setBackground(new Color(255, 255, 153));
    }//GEN-LAST:event_updateProfileBtnMouseEntered

    private void updateProfileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseExited
        updateProfileBtn.setBackground(new Color(255, 239, 153));
    }//GEN-LAST:event_updateProfileBtnMouseExited

    private void updateProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateProfileBtnActionPerformed

    private void inventoryDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryDetailsBtnMouseEntered
        inventoryDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_inventoryDetailsBtnMouseEntered

    private void inventoryDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryDetailsBtnMouseExited

    }//GEN-LAST:event_inventoryDetailsBtnMouseExited

    private void inventoryDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryDetailsBtnActionPerformed

    }//GEN-LAST:event_inventoryDetailsBtnActionPerformed

    private void billTerminaBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn1MouseEntered
        billTerminaBtn1.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_billTerminaBtn1MouseEntered

    private void billTerminaBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn1MouseExited
        billTerminaBtn1.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_billTerminaBtn1MouseExited

    private void billTerminaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billTerminaBtn1ActionPerformed
        this.dispose();
        new BillingFrame(3,uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_billTerminaBtn1ActionPerformed

    private void uDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uDetailsBtnMouseEntered
        uDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_uDetailsBtnMouseEntered

    private void uDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uDetailsBtnMouseExited
        uDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_uDetailsBtnMouseExited

    private void uDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uDetailsBtnActionPerformed
        this.dispose();
        new UserDetailsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_uDetailsBtnActionPerformed

    private void setMenuBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMenuBtnMouseEntered
        setMenuBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_setMenuBtnMouseEntered

    private void setMenuBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMenuBtnMouseExited
        setMenuBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_setMenuBtnMouseExited

    private void setMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMenuBtnActionPerformed
        this.dispose();
        new SetMenuFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_setMenuBtnActionPerformed

    private void suppDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppDetailsBtnMouseEntered
        suppDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_suppDetailsBtnMouseEntered

    private void suppDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppDetailsBtnMouseExited
        suppDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_suppDetailsBtnMouseExited

    private void suppDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppDetailsBtnActionPerformed
        this.dispose();
        new supplierDetails(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_suppDetailsBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new AdminProfile(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        User user = new User();
        int result = user.logOut();
        if (result == JOptionPane.YES_NO_OPTION) {
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void stockDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockDetailsBtnMouseEntered
        stockDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_stockDetailsBtnMouseEntered

    private void stockDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockDetailsBtnMouseExited
        stockDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_stockDetailsBtnMouseExited

    private void stockDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockDetailsBtnActionPerformed
        this.dispose();
        new StockDetailsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_stockDetailsBtnActionPerformed

    private void priceTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtBoxActionPerformed

    private void priceTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTxtBoxKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_priceTxtBoxKeyTyped

    private void clockInBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseEntered
        clockInBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_clockInBtnMouseEntered

    private void clockInBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseExited
        clockInBtn.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_clockInBtnMouseExited

    private void clockInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockInBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clock In?") == JOptionPane.YES_NO_OPTION) {
            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.setClockinTime(LocalTime.now());
            timeSheet.markClockin();
        }
    }//GEN-LAST:event_clockInBtnActionPerformed

    private void clockOffBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseEntered
        clockOffBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clockOffBtnMouseEntered

    private void clockOffBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseExited
        clockOffBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clockOffBtnMouseExited

    private void clockOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockOffBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clok off time") == JOptionPane.YES_NO_OPTION) {

            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());
            timeSheet.setClockoffTime(LocalTime.now());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.markClockoff();

        }
    }//GEN-LAST:event_clockOffBtnActionPerformed

    private void saveInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveInventoryBtnActionPerformed
        String itmName = inventoryNameTxtBox.getText();
        String itmType = itemTypeCmbBox.getSelectedItem().toString();
        String price = priceTxtBox.getText();
        int qty = qtySpinner.getValue();

        String unit = "";
        if (pcsRBtn.isSelected()) {
            unit = "pcs";
        } else if (kgRBtn.isSelected()) {
            unit = "kg";
        } else if (mlRBtn.isSelected()) {
            unit = "ml";
        } else if (lRBtn.isSelected()) {
            unit = "L";
        }

        if (itmName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter item name");
            inventoryNameTxtBox.grabFocus();
        } else if (price.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter item name");
            priceTxtBox.grabFocus();
        } else if (qty == 0) {
            JOptionPane.showMessageDialog(null, "Select a quantity");
        } else if (buttonGroup1.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Select a Unit");
        } else {

            JFrame f = new JFrame();
            if (JOptionPane.showConfirmDialog(f, "Are all the details correct") == JOptionPane.YES_NO_OPTION) {

                InventoryItem item = new InventoryItem(itmName, itmType, Double.parseDouble(price), qty, unit);
                item.addItem();
                loadItem();
                setId();

            }

        }
    }//GEN-LAST:event_saveInventoryBtnActionPerformed

    private void inventoryTableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inventoryTableKeyTyped

    }//GEN-LAST:event_inventoryTableKeyTyped

    private void inventoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTableMouseClicked
        DefaultTableModel df = (DefaultTableModel) inventoryTable.getModel();

        itmId = Integer.parseInt(df.getValueAt(inventoryTable.getSelectedRow(), 0).toString());
        inventoryNameTxtBox.setText(df.getValueAt(inventoryTable.getSelectedRow(), 1).toString());
        itemTypeCmbBox.setSelectedItem(df.getValueAt(inventoryTable.getSelectedRow(), 2).toString());
        priceTxtBox.setText(df.getValueAt(inventoryTable.getSelectedRow(), 3).toString());
        qtySpinner.setValue(Integer.parseInt(df.getValueAt(inventoryTable.getSelectedRow(), 4).toString()));

        String unit = df.getValueAt(inventoryTable.getSelectedRow(), 5).toString();
        if (unit.equals("pcs")) {
            pcsRBtn.setSelected(true);
        } else if (unit.equals("kg")) {
            kgRBtn.setSelected(true);
        } else if (unit.equals("ml")) {
            mlRBtn.setSelected(true);
        } else if (unit.equals("L")) {
            lRBtn.setSelected(true);
        }
    }//GEN-LAST:event_inventoryTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryDetailsFrame("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton billTerminaBtn1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clockInBtn;
    private javax.swing.JButton clockOffBtn;
    private javax.swing.JLabel closeLable;
    private javax.swing.JLabel dateLable;
    private javax.swing.JButton deleteItemBtn;
    private javax.swing.JButton inventoryDetailsBtn;
    private javax.swing.JTextField inventoryIDTxtBox;
    private javax.swing.JTextField inventoryNameTxtBox;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JTextField itemIDTxtBox;
    private javax.swing.JTextField itemNameTxtBox;
    private javax.swing.JComboBox<String> itemTypeCmbBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton kgRBtn;
    private javax.swing.JRadioButton lRBtn;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minimizeLable;
    private javax.swing.JRadioButton mlRBtn;
    private javax.swing.JRadioButton pcsRBtn;
    private javax.swing.JTextField priceTxtBox;
    private com.toedter.components.JSpinField qtySpinner;
    private javax.swing.JButton saveInventoryBtn;
    private javax.swing.JButton searchByIdBtn;
    private javax.swing.JButton searchNameBtn;
    private javax.swing.JButton setMenuBtn;
    private javax.swing.JButton stockDetailsBtn;
    private javax.swing.JButton suppDetailsBtn;
    private javax.swing.JLabel timeLable;
    private javax.swing.JButton uDetailsBtn;
    private javax.swing.JLabel uIDLable;
    private javax.swing.JLabel uNameLable;
    private javax.swing.JButton updateInventoryBtn;
    private javax.swing.JButton updateProfileBtn;
    // End of variables declaration//GEN-END:variables
}
