/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import Others.*;
import Classes.*;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinis
 */
public class IssueSalaryFrame extends javax.swing.JFrame {

    /**
     * Creates new form IssueSalaryFrame
     */
    static Point initialClick;
    int frameNo;
    
    String uid;
    String uname;

    public IssueSalaryFrame(int frameNo, String uid , String uname) {
        initComponents();
        
        this.uid = uid;
        this.uname = uname;

        this.frameNo = frameNo;

        dateLable.setText(DateTime.showDate());
        time();
        disapleOption();
        loadUsers();
        TableUtils.setTableEditableFalse(usersTable, salaryTable1);
        loadSal();
    }

    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    public void disapleOption() {

        uNameTxtBox.disable();
        salaryTxtBox.disable();
        uIdTxtBox.disable();
        usersTable.disable();

    }

    public void loadUsers() {

        try {

            User user = new User();

            ResultSet rs = user.viewUser("*", "");

            DefaultTableModel df = (DefaultTableModel) usersTable.getModel();
            int rc = df.getRowCount();
            for (int i = 0; i < rc; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector();
                String userId = rs.getString("user_id");
                v.add(userId);
                v.add(rs.getString("fname"));
                v.add(rs.getString("role"));
                v.add(rs.getString("salary"));
                df.addRow(v);

            }
            rs.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void loadSal() {

        try {
            
            Salary sal = new Salary();
            ResultSet rs = sal.viewSalary("*", "Inner join expense as e on e.expense_id = s.expense_id inner join user as u on u.user_id = s.user_id", "");
            
            DefaultTableModel df = (DefaultTableModel) salaryTable1.getModel();
            int rc = df.getRowCount();
            for (int i = 0; i < rc; i++) {
                df.removeRow(0);
            }
            
            while (rs.next()) {                
                
                Vector v = new Vector();
                v.add(rs.getString("s.user_id"));
                v.add(rs.getString("e.made_date"));
                v.add(rs.getString("e.made_time"));
                v.add(rs.getString("u.salary"));
                v.add(rs.getString("s.bonus"));
                v.add(rs.getString("s.deductions"));
                v.add(rs.getString("e.amount"));
                df.addRow(v);
                
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        minimizeLable = new javax.swing.JLabel();
        closeLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        uIdTxtBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        uNameTxtBox = new javax.swing.JTextField();
        salaryTxtBox = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        bonusTxtBox = new javax.swing.JTextField();
        dedTxtBox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        serachBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        suIdTxtBox = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        salaryTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 222, 179));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_16px.png"))); // NOI18N
        minimizeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLableMouseExited(evt);
            }
        });
        jPanel3.add(minimizeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 1, 30, 28));

        closeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_16px.png"))); // NOI18N
        closeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLableMouseExited(evt);
            }
        });
        jPanel3.add(closeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1259, 1, 30, 28));

        timeLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 150, 30));

        dateLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        jPanel1.setBackground(new java.awt.Color(242, 224, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(245, 222, 179));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add / Edit Salary");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        uIdTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        uIdTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uIdTxtBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("User Id");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("User Name");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Salary");

        uNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        uNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameTxtBoxActionPerformed(evt);
            }
        });

        salaryTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        salaryTxtBox.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        salaryTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryTxtBoxActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(102, 255, 102));
        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveBtn.setText("Save Salary");
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveBtnMouseExited(evt);
            }
        });
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 102, 102));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtnMouseExited(evt);
            }
        });
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_left_arrow_24px.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Bonus");

        bonusTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bonusTxtBox.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        bonusTxtBox.setText("0");
        bonusTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonusTxtBoxActionPerformed(evt);
            }
        });
        bonusTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bonusTxtBoxKeyTyped(evt);
            }
        });

        dedTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dedTxtBox.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        dedTxtBox.setText("0");
        dedTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dedTxtBoxActionPerformed(evt);
            }
        });
        dedTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dedTxtBoxKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Deduction");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uIdTxtBox)
                    .addComponent(uNameTxtBox, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 164, Short.MAX_VALUE))
                            .addComponent(salaryTxtBox))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(bonusTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dedTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salaryTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dedTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bonusTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 590));

        jPanel5.setBackground(new java.awt.Color(245, 222, 179));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("User Details");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User Id", "First Name", "Job Role", "Salary"
            }
        ));
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(usersTable);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Use Id");

        serachBtn.setBackground(new java.awt.Color(102, 255, 102));
        serachBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        serachBtn.setText("Search");
        serachBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serachBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serachBtnMouseExited(evt);
            }
        });
        serachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serachBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Salary Details");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        suIdTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        suIdTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suIdTxtBoxActionPerformed(evt);
            }
        });

        salaryTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User Id", "Made Date", "Made Time", "Salary", "Bonus", "Deductions", "Net Salary"
            }
        ));
        jScrollPane5.setViewportView(salaryTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(suIdTxtBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 10, 620, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseClicked
        this.setExtendedState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLableMouseClicked

    private void minimizeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseEntered
        minimizeLable.setOpaque(true);
        minimizeLable.setBackground(new Color(210, 180, 140));
        minimizeLable.repaint();
    }//GEN-LAST:event_minimizeLableMouseEntered

    private void minimizeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseExited
        minimizeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_minimizeLableMouseExited

    private void closeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseClicked
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to exit?") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeLableMouseClicked

    private void closeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseEntered
        closeLable.setOpaque(true);
        closeLable.setBackground(new Color(210, 180, 140));
        closeLable.repaint();
    }//GEN-LAST:event_closeLableMouseEntered

    private void closeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseExited
        closeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_closeLableMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;
        int x = getLocation().x + xMoved;
        int y = getLocation().y + yMoved;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanel3MousePressed

    private void serachBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serachBtnMouseEntered
        serachBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_serachBtnMouseEntered

    private void serachBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serachBtnMouseExited
        serachBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_serachBtnMouseExited

    private void serachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serachBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serachBtnActionPerformed

    private void uIdTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uIdTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uIdTxtBoxActionPerformed

    private void uNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameTxtBoxActionPerformed

    private void salaryTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryTxtBoxActionPerformed

    private void saveBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseEntered
        saveBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_saveBtnMouseEntered

    private void saveBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseExited
        saveBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_saveBtnMouseExited

    private void clearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseEntered
        clearBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clearBtnMouseEntered

    private void clearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseExited
        clearBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clearBtnMouseExited

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        uIdTxtBox.setText("");
        salaryTxtBox.setText("");
        uNameTxtBox.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new AccountantProfile(uid,uname).setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void suIdTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suIdTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suIdTxtBoxActionPerformed

    private void bonusTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonusTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bonusTxtBoxActionPerformed

    private void dedTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dedTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dedTxtBoxActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (bonusTxtBox.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "If there isn't bonus, please enter 0");
        } else if (dedTxtBox.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "If there isn't a deduction, please enter 0");
        } else if (uIdTxtBox.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a User to give salary");
        } else {

            java.sql.Date mkdate = java.sql.Date.valueOf(LocalDate.now());
            Time mktime = Time.valueOf(LocalTime.now());

            double totAmount = Double.parseDouble(salaryTxtBox.getText()) + Double.parseDouble(bonusTxtBox.getText()) - Double.parseDouble(dedTxtBox.getText());

            Expense exp = new Expense("Salary", mkdate, mktime, totAmount);

            try {
                exp.addExpence();

//                String getNewId = "SELECT LAST_INSERT_ID() AS id";
                String query = "SELECT expense_id FROM expense WHERE type = ? AND made_date = ? AND made_time = ? AND amount = ?";
                ResultSet rs = MyConn.search(query, "Salary", mkdate, mktime, totAmount);
                int newExpenseId = -1;
                if (rs.next()) {
                    newExpenseId = rs.getInt("expense_id");
                }

                if (newExpenseId == -1) {
                    JOptionPane.showMessageDialog(null, "Error retrieving the new expense ID.");
                    return;
                }

                System.out.println(newExpenseId);

                Salary sal = new Salary(newExpenseId, uIdTxtBox.getText(), Double.parseDouble(bonusTxtBox.getText()), Double.parseDouble(dedTxtBox.getText()));
                sal.addSalary();

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked
        usersTable.setEnabled(true);
        DefaultTableModel df = (DefaultTableModel) usersTable.getModel();
        int selectedRow = usersTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a user from the table.");
        } else {
            uIdTxtBox.setText(df.getValueAt(selectedRow, 0).toString());
            uNameTxtBox.setText(df.getValueAt(selectedRow, 1).toString());
            salaryTxtBox.setText(df.getValueAt(selectedRow, 3).toString());
        }

    }//GEN-LAST:event_usersTableMouseClicked

    private void bonusTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonusTxtBoxKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_bonusTxtBoxKeyTyped

    private void dedTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dedTxtBoxKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_dedTxtBoxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueSalaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueSalaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueSalaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueSalaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueSalaryFrame(0, "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bonusTxtBox;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel closeLable;
    private javax.swing.JLabel dateLable;
    private javax.swing.JTextField dedTxtBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel minimizeLable;
    private javax.swing.JTable salaryTable1;
    private javax.swing.JTextField salaryTxtBox;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton serachBtn;
    private javax.swing.JTextField suIdTxtBox;
    private javax.swing.JLabel timeLable;
    private javax.swing.JTextField uIdTxtBox;
    private javax.swing.JTextField uNameTxtBox;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
