/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Others.*;
import Classes.*;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 *
 * @author dinis
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    static Point initialClick;

    public LoginFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameTxtBox = new javax.swing.JTextField();
        pwdTxtBox = new javax.swing.JPasswordField();
        pwdLable = new javax.swing.JLabel();
        uNameLable = new javax.swing.JLabel();
        showPwdChkBox = new javax.swing.JCheckBox();
        loginBtn = new javax.swing.JButton();
        clearBtn1 = new javax.swing.JButton();
        forgotPwdLable = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        closeLable = new javax.swing.JLabel();
        minimizeLable = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(210, 180, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(101, 67, 33));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CafeLogo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 222, 179));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 280, 51));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(245, 222, 179));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 280, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 222, 179));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CAFE MANAGEMENT");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 280, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(245, 222, 179));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SYSTEM");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 280, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 570));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 46)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGIN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 480, -1));

        userNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        userNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtBoxActionPerformed(evt);
            }
        });
        jPanel1.add(userNameTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 430, 50));

        pwdTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(pwdTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 430, 50));

        pwdLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pwdLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_key_30px.png"))); // NOI18N
        pwdLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdLableMouseClicked(evt);
            }
        });
        jPanel1.add(pwdLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 40, 50));

        uNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uNameLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_user_30px_1.png"))); // NOI18N
        uNameLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uNameLableMouseClicked(evt);
            }
        });
        jPanel1.add(uNameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 270, 30, 50));

        showPwdChkBox.setBackground(new java.awt.Color(210, 180, 140));
        showPwdChkBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        showPwdChkBox.setText("Show Password");
        showPwdChkBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showPwdChkBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showPwdChkBoxMouseExited(evt);
            }
        });
        showPwdChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPwdChkBoxActionPerformed(evt);
            }
        });
        jPanel1.add(showPwdChkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 120, -1));

        loginBtn.setBackground(new java.awt.Color(30, 144, 255));
        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 230, 30));

        clearBtn1.setBackground(new java.awt.Color(255, 153, 153));
        clearBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearBtn1.setText("Clear");
        clearBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtn1MouseExited(evt);
            }
        });
        clearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 150, 30));

        forgotPwdLable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        forgotPwdLable.setText("Forgot Password");
        forgotPwdLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotPwdLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotPwdLableMouseExited(evt);
            }
        });
        jPanel1.add(forgotPwdLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("If you don't have any account please contact our administrator");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 420, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 400, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 570));

        jPanel3.setBackground(new java.awt.Color(245, 222, 179));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_16px.png"))); // NOI18N
        closeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLableMouseExited(evt);
            }
        });
        jPanel3.add(closeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 1, 30, 28));

        minimizeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_16px.png"))); // NOI18N
        minimizeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLableMouseExited(evt);
            }
        });
        jPanel3.add(minimizeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 1, 30, 28));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtBoxActionPerformed

    private void showPwdChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPwdChkBoxActionPerformed
        if (showPwdChkBox.isSelected()) {
            pwdTxtBox.setEchoChar((char) 0);
        } else {
            pwdTxtBox.setEchoChar('*');
        }
    }//GEN-LAST:event_showPwdChkBoxActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        User user = new User();
        user.setId(userNameTxtBox.getText());
        user.setPassword(pwdTxtBox.getText());
        user.logIn();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void clearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn1ActionPerformed
        pwdTxtBox.setText("");
        userNameTxtBox.setText("");
    }//GEN-LAST:event_clearBtn1ActionPerformed

    private void minimizeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseClicked
        this.setExtendedState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLableMouseClicked

    private void closeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseClicked
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to exit?") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeLableMouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;
        int x = getLocation().x + xMoved;
        int y = getLocation().y + yMoved;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void closeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseEntered
        closeLable.setOpaque(true);
        closeLable.setBackground(new Color(210, 180, 140));
        closeLable.repaint();
    }//GEN-LAST:event_closeLableMouseEntered

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        loginBtn.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        loginBtn.setBackground(new Color(30, 144, 255));
    }//GEN-LAST:event_loginBtnMouseExited

    private void clearBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtn1MouseEntered
        clearBtn1.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clearBtn1MouseEntered

    private void clearBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtn1MouseExited
        clearBtn1.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_clearBtn1MouseExited

    private void closeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseExited
        closeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_closeLableMouseExited

    private void minimizeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseEntered
        minimizeLable.setOpaque(true);
        minimizeLable.setBackground(new Color(210, 180, 140));
        minimizeLable.repaint();
    }//GEN-LAST:event_minimizeLableMouseEntered

    private void minimizeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseExited
        minimizeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_minimizeLableMouseExited

    private void forgotPwdLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPwdLableMouseEntered
        forgotPwdLable.setForeground(new Color(112, 128, 144));
    }//GEN-LAST:event_forgotPwdLableMouseEntered

    private void forgotPwdLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPwdLableMouseExited
        forgotPwdLable.setForeground(Color.BLACK);
    }//GEN-LAST:event_forgotPwdLableMouseExited

    private void uNameLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uNameLableMouseClicked
        userNameTxtBox.grabFocus();
    }//GEN-LAST:event_uNameLableMouseClicked

    private void pwdLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdLableMouseClicked
        pwdTxtBox.grabFocus();
    }//GEN-LAST:event_pwdLableMouseClicked

    private void showPwdChkBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPwdChkBoxMouseEntered
        showPwdChkBox.setForeground(new Color(112, 128, 144));
    }//GEN-LAST:event_showPwdChkBoxMouseEntered

    private void showPwdChkBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPwdChkBoxMouseExited
        showPwdChkBox.setForeground(Color.BLACK);
    }//GEN-LAST:event_showPwdChkBoxMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn1;
    private javax.swing.JLabel closeLable;
    private javax.swing.JLabel forgotPwdLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel minimizeLable;
    private javax.swing.JLabel pwdLable;
    private javax.swing.JPasswordField pwdTxtBox;
    private javax.swing.JCheckBox showPwdChkBox;
    private javax.swing.JLabel uNameLable;
    private javax.swing.JTextField userNameTxtBox;
    // End of variables declaration//GEN-END:variables

    private void setOpacity(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
