/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import Others.*;
import Classes.*;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.ResultSet;
import java.time.LocalTime;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinis
 */
public class MakeComplainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MakeComplainFrame
     */
    static Point initialClick;

    int frameNo;

    public MakeComplainFrame(int frameNo) {
        initComponents();

        this.frameNo = frameNo;

        dateLable.setText(DateTime.showDate());
        time();
        loadComplaints();
        hideIdColumn();
    }

    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    public void loadComplaints() {

        try {

            Complaint cmp = new Complaint();
            ResultSet rs = cmp.viewComplaint("*", "");

            DefaultTableModel df = (DefaultTableModel) complaintTable.getModel();
            int rc = df.getRowCount();
            for (int i = 0; i < rc; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector(); 
                v.add(rs.getString("description"));
                v.add(rs.getString("made_date"));
                v.add(rs.getString("status"));
                v.add(rs.getString("comp_id"));
                df.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void hideIdColumn() {

        complaintTable.getColumnModel().getColumn(3).setMinWidth(0);
        complaintTable.getColumnModel().getColumn(3).setMaxWidth(0);
        complaintTable.getColumnModel().getColumn(3).setWidth(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        minimizeLable = new javax.swing.JLabel();
        closeLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        complaintTable = new javax.swing.JTable();
        deleteCmptBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        problemTxtBox = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        makeCmptBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        updateProfileBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uNameLable = new javax.swing.JLabel();
        uIDLable = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        billTerminaBtn1 = new javax.swing.JButton();
        requestLeaveBtn = new javax.swing.JButton();
        makeComplaintBtn = new javax.swing.JButton();
        clockInBtn = new javax.swing.JButton();
        clockOffBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 222, 179));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_16px.png"))); // NOI18N
        minimizeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLableMouseExited(evt);
            }
        });
        jPanel3.add(minimizeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 1, 30, 28));

        closeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_16px.png"))); // NOI18N
        closeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLableMouseExited(evt);
            }
        });
        jPanel3.add(closeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1259, 1, 30, 28));

        timeLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 150, 30));

        dateLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        jPanel1.setBackground(new java.awt.Color(242, 224, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(245, 222, 179));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        complaintTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Description", "Made Date", "Status", "Id"
            }
        ));
        jScrollPane2.setViewportView(complaintTable);

        deleteCmptBtn.setBackground(new java.awt.Color(255, 102, 102));
        deleteCmptBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteCmptBtn.setText("Delete");
        deleteCmptBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteCmptBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteCmptBtnMouseExited(evt);
            }
        });
        deleteCmptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCmptBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Complaint Details");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(deleteCmptBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteCmptBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(525, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, 590));

        jPanel6.setBackground(new java.awt.Color(245, 222, 179));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Make Your Complaint");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        problemTxtBox.setColumns(20);
        problemTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        problemTxtBox.setRows(5);
        jScrollPane1.setViewportView(problemTxtBox);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Describe your problem");

        makeCmptBtn.setBackground(new java.awt.Color(102, 255, 102));
        makeCmptBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        makeCmptBtn.setText("Make Complain");
        makeCmptBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makeCmptBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                makeCmptBtnMouseExited(evt);
            }
        });
        makeCmptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeCmptBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 102, 102));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtnMouseExited(evt);
            }
        });
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addComponent(makeCmptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 307, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(makeCmptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearBtn)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 460, -1));

        menuPanel.setBackground(new java.awt.Color(210, 180, 140));
        menuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(210, 180, 140));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));

        updateProfileBtn.setBackground(new java.awt.Color(255, 239, 153));
        updateProfileBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateProfileBtn.setText("Update Profile");
        updateProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseExited(evt);
            }
        });
        updateProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileBtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_customer_40px.png"))); // NOI18N

        uNameLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uNameLable.setText("Employee Name");
        uNameLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        uIDLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uIDLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uIDLable.setText("Employee Id");
        uIDLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uIDLable, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(uIDLable, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(uNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 140));

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_left_arrow_24px.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        menuPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 140, 30));

        logOutBtn.setBackground(new java.awt.Color(255, 153, 153));
        logOutBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtnMouseExited(evt);
            }
        });
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        menuPanel.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 140, 30));

        billTerminaBtn1.setBackground(new java.awt.Color(64, 224, 208));
        billTerminaBtn1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        billTerminaBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_bill_26px.png"))); // NOI18N
        billTerminaBtn1.setText(" Billing Terminal");
        billTerminaBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billTerminaBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billTerminaBtn1MouseExited(evt);
            }
        });
        billTerminaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billTerminaBtn1ActionPerformed(evt);
            }
        });
        menuPanel.add(billTerminaBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 300, 50));

        requestLeaveBtn.setBackground(new java.awt.Color(64, 224, 208));
        requestLeaveBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        requestLeaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_leave_24px.png"))); // NOI18N
        requestLeaveBtn.setText(" Request Leave");
        requestLeaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                requestLeaveBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                requestLeaveBtnMouseExited(evt);
            }
        });
        requestLeaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestLeaveBtnActionPerformed(evt);
            }
        });
        menuPanel.add(requestLeaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 300, 50));

        makeComplaintBtn.setBackground(new java.awt.Color(51, 204, 255));
        makeComplaintBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        makeComplaintBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_complaint_30px.png"))); // NOI18N
        makeComplaintBtn.setText(" Make Complaint");
        makeComplaintBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makeComplaintBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                makeComplaintBtnMouseExited(evt);
            }
        });
        makeComplaintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeComplaintBtnActionPerformed(evt);
            }
        });
        menuPanel.add(makeComplaintBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 300, 50));

        clockInBtn.setBackground(new java.awt.Color(153, 255, 153));
        clockInBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_clock_checked_24px.png"))); // NOI18N
        clockInBtn.setText(" Mark Clock in");
        clockInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockInBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockInBtnMouseExited(evt);
            }
        });
        clockInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockInBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 300, 50));

        clockOffBtn.setBackground(new java.awt.Color(255, 102, 102));
        clockOffBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockOffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_alarm_off_24px.png"))); // NOI18N
        clockOffBtn.setText(" Mark Clock off");
        clockOffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseExited(evt);
            }
        });
        clockOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockOffBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockOffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 300, 50));

        jPanel1.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseClicked
        this.setExtendedState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLableMouseClicked

    private void minimizeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseEntered
        minimizeLable.setOpaque(true);
        minimizeLable.setBackground(new Color(210, 180, 140));
        minimizeLable.repaint();
    }//GEN-LAST:event_minimizeLableMouseEntered

    private void minimizeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseExited
        minimizeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_minimizeLableMouseExited

    private void closeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseClicked
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to exit?") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeLableMouseClicked

    private void closeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseEntered
        closeLable.setOpaque(true);
        closeLable.setBackground(new Color(210, 180, 140));
        closeLable.repaint();
    }//GEN-LAST:event_closeLableMouseEntered

    private void closeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseExited
        closeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_closeLableMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;
        int x = getLocation().x + xMoved;
        int y = getLocation().y + yMoved;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanel3MousePressed

    private void deleteCmptBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCmptBtnMouseEntered
        deleteCmptBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_deleteCmptBtnMouseEntered

    private void deleteCmptBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCmptBtnMouseExited
        deleteCmptBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_deleteCmptBtnMouseExited

    private void deleteCmptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCmptBtnActionPerformed
        DefaultTableModel df = (DefaultTableModel) complaintTable.getModel();

        if (complaintTable.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Please select a complaint to delete");
        } else {
            
            Complaint cmp = new Complaint();
            cmp.setComId(Integer.parseInt(df.getValueAt(complaintTable.getSelectedRow(), 3).toString()));
            cmp.removeComplaint();
            loadComplaints();
            
        }
    }//GEN-LAST:event_deleteCmptBtnActionPerformed

    private void clearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseEntered
        clearBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clearBtnMouseEntered

    private void clearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseExited
        clearBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clearBtnMouseExited

    private void makeCmptBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeCmptBtnMouseEntered
        makeCmptBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_makeCmptBtnMouseEntered

    private void makeCmptBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeCmptBtnMouseExited
        makeCmptBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_makeCmptBtnMouseExited

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        problemTxtBox.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void updateProfileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseEntered
        updateProfileBtn.setBackground(new Color(255, 255, 153));
    }//GEN-LAST:event_updateProfileBtnMouseEntered

    private void updateProfileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseExited
        updateProfileBtn.setBackground(new Color(255, 239, 153));
    }//GEN-LAST:event_updateProfileBtnMouseExited

    private void updateProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateProfileBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        if (frameNo == 1) {

            this.dispose();
            new EmployeeProfile(uIDLable.getText(), uNameLable.getText()).setVisible(true);

        } else if (frameNo == 2) {

            this.dispose();
            new chefProfile(uIDLable.getText(), uNameLable.getText()).setVisible(true);

        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        User user = new User();
        int result = user.logOut();
        if (result == JOptionPane.YES_NO_OPTION) {
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void billTerminaBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn1MouseEntered
        billTerminaBtn1.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_billTerminaBtn1MouseEntered

    private void billTerminaBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn1MouseExited
        billTerminaBtn1.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_billTerminaBtn1MouseExited

    private void billTerminaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billTerminaBtn1ActionPerformed
        this.dispose();
        new BillingFrame(frameNo,uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_billTerminaBtn1ActionPerformed

    private void requestLeaveBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestLeaveBtnMouseEntered
        requestLeaveBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_requestLeaveBtnMouseEntered

    private void requestLeaveBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestLeaveBtnMouseExited
        requestLeaveBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_requestLeaveBtnMouseExited

    private void requestLeaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestLeaveBtnActionPerformed
        this.dispose();
        new RequestLeaveFrame(frameNo, "", "").setVisible(true);
    }//GEN-LAST:event_requestLeaveBtnActionPerformed

    private void makeComplaintBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeComplaintBtnMouseEntered
        makeComplaintBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_makeComplaintBtnMouseEntered

    private void makeComplaintBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeComplaintBtnMouseExited

    }//GEN-LAST:event_makeComplaintBtnMouseExited

    private void makeComplaintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeComplaintBtnActionPerformed

    }//GEN-LAST:event_makeComplaintBtnActionPerformed

    private void makeCmptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeCmptBtnActionPerformed
        if (problemTxtBox.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter your problem");
            problemTxtBox.grabFocus();
        } else {

            Complaint cmp = new Complaint();

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd");

            cmp.setDescription(problemTxtBox.getText());
            cmp.setMDate(LocalDate.parse(dateLable.getText(), formatter));
            cmp.setStatus("Pending");

            cmp.makeComplaint();
            loadComplaints();

        }
    }//GEN-LAST:event_makeCmptBtnActionPerformed

    private void clockInBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseEntered
        clockInBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_clockInBtnMouseEntered

    private void clockInBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseExited
        clockInBtn.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_clockInBtnMouseExited

    private void clockInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockInBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clock In?") == JOptionPane.YES_NO_OPTION) {
            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.setClockinTime(LocalTime.now());
            timeSheet.markClockin();
        }
    }//GEN-LAST:event_clockInBtnActionPerformed

    private void clockOffBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseEntered
        clockOffBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clockOffBtnMouseEntered

    private void clockOffBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseExited
        clockOffBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clockOffBtnMouseExited

    private void clockOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockOffBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clok off time") == JOptionPane.YES_NO_OPTION) {

            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());
            timeSheet.setClockoffTime(LocalTime.now());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.markClockoff();

        }
    }//GEN-LAST:event_clockOffBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeComplainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeComplainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeComplainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeComplainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeComplainFrame(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton billTerminaBtn1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clockInBtn;
    private javax.swing.JButton clockOffBtn;
    private javax.swing.JLabel closeLable;
    private javax.swing.JTable complaintTable;
    private javax.swing.JLabel dateLable;
    private javax.swing.JButton deleteCmptBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton makeCmptBtn;
    private javax.swing.JButton makeComplaintBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minimizeLable;
    private javax.swing.JTextArea problemTxtBox;
    private javax.swing.JButton requestLeaveBtn;
    private javax.swing.JLabel timeLable;
    private javax.swing.JLabel uIDLable;
    private javax.swing.JLabel uNameLable;
    private javax.swing.JButton updateProfileBtn;
    // End of variables declaration//GEN-END:variables
}
