/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import Others.*;
import Classes.*;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;

/**
 *
 * @author dinis
 */
public class NewBulkOrderFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewBulkOrderFrame
     */
    static Point initialClick;

    String uid;
    String uname;

    public NewBulkOrderFrame(String uid, String uname) {
        initComponents();

        this.uid = uid;
        this.uname = uname;

        dateLable.setText(DateTime.showDate());
        time();
        loadProducts();
        // TableUtils.setTableEditableFalse(productInfoTable, cartTable);
    }

    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    public void loadProducts() {

        try {

            Product product = new Product();
            ResultSet rs = product.viewProduct("*", "availability = ?", 1);

            DefaultTableModel df = (DefaultTableModel) productInfoTable.getModel();
            int rc = df.getRowCount();
            for (int i = 0; i < rc; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("product_id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("price"));
                df.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    public void setTotal() {
        DefaultTableModel df = (DefaultTableModel) cartTable.getModel();
        int rowC = df.getRowCount();
        double total = 0;
        for (int i = 0; i < rowC; i++) {
            total += Double.parseDouble(df.getValueAt(i, 3).toString());
            totalCostTxtBox.setText(String.valueOf(total));

            if (total >= 3000) {
                discountTxtBox.setText(30 + "");
            } else {
                discountTxtBox.setText(2 + "");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        minimizeLable = new javax.swing.JLabel();
        closeLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        bOrderIdTxtBox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totalCostTxtBox = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        discountTxtBox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        removeCartBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        saveOrderBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cashRBtn = new javax.swing.JRadioButton();
        cardRBtn = new javax.swing.JRadioButton();
        dueDateChooser = new com.toedter.calendar.JDateChooser();
        customerIDTxtBox1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sPNameTxtBox = new javax.swing.JTextField();
        serachStockBtn2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pNameTxtBox = new javax.swing.JTextField();
        qtySpinner = new com.toedter.components.JSpinField();
        jLabel10 = new javax.swing.JLabel();
        addToCartBtn = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        productInfoTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        priceTxtBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 222, 179));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_16px.png"))); // NOI18N
        minimizeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLableMouseExited(evt);
            }
        });
        jPanel3.add(minimizeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 1, 30, 28));

        closeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_16px.png"))); // NOI18N
        closeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLableMouseExited(evt);
            }
        });
        jPanel3.add(closeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1259, 1, 30, 28));

        timeLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 150, 30));

        dateLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        jPanel1.setBackground(new java.awt.Color(242, 224, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(245, 222, 179));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("New Bulk Order");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 18, 824, 37));

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Unit Price", "Quantity", "Total"
            }
        ));
        jScrollPane6.setViewportView(cartTable);

        jPanel5.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 132, 560, 200));

        bOrderIdTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bOrderIdTxtBox.setText("2");
        bOrderIdTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrderIdTxtBoxActionPerformed(evt);
            }
        });
        jPanel5.add(bOrderIdTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 88, 387, 32));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Bulk Order Id");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 67, -1, -1));

        totalCostTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        totalCostTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCostTxtBoxActionPerformed(evt);
            }
        });
        jPanel5.add(totalCostTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 405, 820, 32));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Total Cost");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 384, -1, -1));

        discountTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        discountTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTxtBoxActionPerformed(evt);
            }
        });
        jPanel5.add(discountTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 464, 562, 32));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Discount");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 443, -1, -1));

        removeCartBtn.setBackground(new java.awt.Color(255, 102, 102));
        removeCartBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        removeCartBtn.setText("Remove From Cart");
        removeCartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeCartBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeCartBtnMouseExited(evt);
            }
        });
        removeCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCartBtnActionPerformed(evt);
            }
        });
        jPanel5.add(removeCartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 344, 560, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Due Date");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 508, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Customer Id");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 67, -1, -1));

        saveOrderBtn.setBackground(new java.awt.Color(102, 255, 102));
        saveOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveOrderBtn.setText("Save Order");
        saveOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveOrderBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveOrderBtnMouseExited(evt);
            }
        });
        jPanel5.add(saveOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 240, 50));

        clearBtn.setBackground(new java.awt.Color(255, 102, 102));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtnMouseExited(evt);
            }
        });
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel5.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 531, 240, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Select a Payment Method");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 230, -1));

        buttonGroup1.add(cashRBtn);
        cashRBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cashRBtn.setText("Cash");
        jPanel5.add(cashRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        buttonGroup1.add(cardRBtn);
        cardRBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cardRBtn.setText("Card");
        jPanel5.add(cardRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));
        jPanel5.add(dueDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 560, 30));

        customerIDTxtBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        customerIDTxtBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIDTxtBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(customerIDTxtBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 88, 425, 32));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 10, 840, 590));

        jPanel4.setBackground(new java.awt.Color(245, 222, 179));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Products");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Product Name");

        sPNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sPNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPNameTxtBoxActionPerformed(evt);
            }
        });
        sPNameTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sPNameTxtBoxKeyTyped(evt);
            }
        });

        serachStockBtn2.setBackground(new java.awt.Color(102, 255, 102));
        serachStockBtn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        serachStockBtn2.setText("Search");
        serachStockBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serachStockBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serachStockBtn2MouseExited(evt);
            }
        });
        serachStockBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serachStockBtn2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Product");

        pNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameTxtBoxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Quantity");

        addToCartBtn.setBackground(new java.awt.Color(204, 255, 153));
        addToCartBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addToCartBtn.setText("Add to Cart");
        addToCartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addToCartBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addToCartBtnMouseExited(evt);
            }
        });
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });

        productInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Id", "Name", "Price"
            }
        ));
        jScrollPane7.setViewportView(productInfoTable);

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_left_arrow_24px.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Product Price");

        priceTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        priceTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(sPNameTxtBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serachStockBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pNameTxtBox)
                    .addComponent(addToCartBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceTxtBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(140, 140, 140)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(qtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sPNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serachStockBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addToCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(224, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseClicked
        this.setExtendedState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLableMouseClicked

    private void minimizeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseEntered
        minimizeLable.setOpaque(true);
        minimizeLable.setBackground(new Color(210, 180, 140));
        minimizeLable.repaint();
    }//GEN-LAST:event_minimizeLableMouseEntered

    private void minimizeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseExited
        minimizeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_minimizeLableMouseExited

    private void closeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseClicked
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to exit?") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeLableMouseClicked

    private void closeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseEntered
        closeLable.setOpaque(true);
        closeLable.setBackground(new Color(210, 180, 140));
        closeLable.repaint();
    }//GEN-LAST:event_closeLableMouseEntered

    private void closeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseExited
        closeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_closeLableMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;
        int x = getLocation().x + xMoved;
        int y = getLocation().y + yMoved;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanel3MousePressed

    private void removeCartBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCartBtnMouseEntered
        removeCartBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_removeCartBtnMouseEntered

    private void removeCartBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCartBtnMouseExited
        removeCartBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_removeCartBtnMouseExited

    private void removeCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCartBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCartBtnActionPerformed

    private void bOrderIdTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrderIdTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bOrderIdTxtBoxActionPerformed

    private void discountTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountTxtBoxActionPerformed

    private void totalCostTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCostTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalCostTxtBoxActionPerformed

    private void saveOrderBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveOrderBtnMouseEntered
        saveOrderBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_saveOrderBtnMouseEntered

    private void saveOrderBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveOrderBtnMouseExited
        saveOrderBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_saveOrderBtnMouseExited

    private void clearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseEntered
        clearBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clearBtnMouseEntered

    private void clearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseExited
        clearBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clearBtnMouseExited

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        customerIDTxtBox1.setText("");
        totalCostTxtBox.setText("");
        discountTxtBox.setText("");
        dueDateChooser.setDate(null);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void customerIDTxtBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIDTxtBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIDTxtBox1ActionPerformed

    private void sPNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sPNameTxtBoxActionPerformed

    private void sPNameTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sPNameTxtBoxKeyTyped
        try {

            Product pdct = new Product();
            ResultSet rs = pdct.viewProduct("*", "name like ? and availability = ?", "%" + sPNameTxtBox.getText() + "%", 1);
            DefaultTableModel df = (DefaultTableModel) productInfoTable.getModel();
            int rc = df.getRowCount();
            for (int i = 0; i < rc; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("product_id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("price"));
                df.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_sPNameTxtBoxKeyTyped

    private void serachStockBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serachStockBtn2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_serachStockBtn2MouseEntered

    private void serachStockBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serachStockBtn2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_serachStockBtn2MouseExited

    private void serachStockBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serachStockBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serachStockBtn2ActionPerformed

    private void pNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameTxtBoxActionPerformed

    private void addToCartBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartBtnMouseEntered
        addToCartBtn.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_addToCartBtnMouseEntered

    private void addToCartBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartBtnMouseExited
        addToCartBtn.setBackground(new Color(204, 255, 153));
    }//GEN-LAST:event_addToCartBtnMouseExited

    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        if (pNameTxtBox.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please select a product");
        } else if (qtySpinner.getValue() == 0) {
            JOptionPane.showMessageDialog(null, "Quantity cannot be 0");
        } else {
            DefaultTableModel df = (DefaultTableModel) cartTable.getModel();
            int rowCount = df.getRowCount();
            boolean duplicateFound = false;

            // Iterate over all rows to find if the product is already in the cart
            for (int i = 0; i < rowCount; i++) {
                Object cellValue = df.getValueAt(i, 0);
                if (cellValue != null && pNameTxtBox.getText().equals(cellValue.toString())) {
                    duplicateFound = true;
                    break;
                }
            }

            if (duplicateFound) {
                JOptionPane.showMessageDialog(null, "Already in the cart");
            } else {
                double price = Double.parseDouble(priceTxtBox.getText());
                int quantity = qtySpinner.getValue();
                double total = price * quantity;

                Object[] data = {pNameTxtBox.getText(), priceTxtBox.getText(), quantity, total};
                df.addRow(data);
                //pList.add(pid);
                setTotal();
            }
        }

    }//GEN-LAST:event_addToCartBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new BulkOrderDetailsFrame(uid, uname).setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void priceTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBulkOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBulkOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBulkOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBulkOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBulkOrderFrame("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JTextField bOrderIdTxtBox;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cardRBtn;
    private javax.swing.JTable cartTable;
    private javax.swing.JRadioButton cashRBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel closeLable;
    private javax.swing.JTextField customerIDTxtBox1;
    private javax.swing.JLabel dateLable;
    private javax.swing.JTextField discountTxtBox;
    private com.toedter.calendar.JDateChooser dueDateChooser;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel minimizeLable;
    private javax.swing.JTextField pNameTxtBox;
    private javax.swing.JTextField priceTxtBox;
    private javax.swing.JTable productInfoTable;
    private com.toedter.components.JSpinField qtySpinner;
    private javax.swing.JButton removeCartBtn;
    private javax.swing.JTextField sPNameTxtBox;
    private javax.swing.JButton saveOrderBtn;
    private javax.swing.JButton serachStockBtn2;
    private javax.swing.JLabel timeLable;
    private javax.swing.JTextField totalCostTxtBox;
    // End of variables declaration//GEN-END:variables
}
