/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import Others.*;
import Classes.*;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinis
 */
public class ProductDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProductDetailsFrame
     */
    static Point initialClick;

    public ProductDetailsFrame(String uid, String uname) {
        initComponents();
        uIDLable.setText(uid);
        uNameLable.setText(uname);

        dateLable.setText(DateTime.showDate());
        time();
        incrementPId();
        loadProducts("");
        adjustTbColums();

    }

    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    public void incrementPId() {

        pIDTxtBox.setText("PDCT-1000");
        try {

            String getID = "Select * from product";
            ResultSet rs = MyConn.search(getID);
            while (rs.next()) {

                String id = rs.getString("product_id");
                String splitID[] = id.split("-");
                int lastVal = Integer.parseInt(splitID[1]);
                lastVal++;
                pIDTxtBox.setText("PDCT-" + lastVal);

            }

            pIDTxtBox.disable();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void loadProducts(String condition, Object... values) {

        try {

            Product pdct = new Product();
            ResultSet rs = pdct.viewProduct("*", condition, values);

            DefaultTableModel df = (DefaultTableModel) productDetailsTable.getModel();
            int rc = df.getRowCount();
            for (int i = 0; i < rc; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("product_id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("Description"));
                v.add(rs.getString("price"));
                v.add(rs.getString("Category"));
                boolean avail = rs.getBoolean("availability");
                if (avail) {
                    v.add("Yes");
                } else {
                    v.add("No");
                }

                df.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void adjustTbColums() {

        productDetailsTable.getColumnModel().getColumn(0).setPreferredWidth(80);
        productDetailsTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        productDetailsTable.getColumnModel().getColumn(2).setPreferredWidth(200);
        productDetailsTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        productDetailsTable.getColumnModel().getColumn(4).setPreferredWidth(70);
        productDetailsTable.getColumnModel().getColumn(5).setPreferredWidth(40);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        minimizeLable = new javax.swing.JLabel();
        closeLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pIDTxtBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pNameTxtBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        priceTxtBox = new javax.swing.JTextField();
        saveProductBtn = new javax.swing.JButton();
        updateProductBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        categoryCmbBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTxtBox = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        productDetailsTable = new javax.swing.JTable();
        serachNameBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        spNameTxtBox = new javax.swing.JTextField();
        deleteProductBtntBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        addIngreBtn = new javax.swing.JButton();
        categoryCmbBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        updateProfileBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uNameLable = new javax.swing.JLabel();
        uIDLable = new javax.swing.JLabel();
        assignTaskBtn = new javax.swing.JButton();
        bulkOrderBtn = new javax.swing.JButton();
        productDetailsBtn = new javax.swing.JButton();
        billTerminaBtn2 = new javax.swing.JButton();
        sendNoteBtn = new javax.swing.JButton();
        empDetailsBtn = new javax.swing.JButton();
        viewLogBtn = new javax.swing.JButton();
        markExpencessBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        clockInBtn = new javax.swing.JButton();
        clockOffBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 222, 179));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_16px.png"))); // NOI18N
        minimizeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLableMouseExited(evt);
            }
        });
        jPanel3.add(minimizeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 1, 30, 28));

        closeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_16px.png"))); // NOI18N
        closeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLableMouseExited(evt);
            }
        });
        jPanel3.add(closeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1259, 1, 30, 28));

        timeLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 150, 30));

        dateLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        jPanel1.setBackground(new java.awt.Color(242, 224, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(245, 222, 179));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add / Edit Product");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Product Id");

        pIDTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pIDTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pIDTxtBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Product Name");

        pNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameTxtBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Product Price");

        priceTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        priceTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtBoxActionPerformed(evt);
            }
        });
        priceTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceTxtBoxKeyTyped(evt);
            }
        });

        saveProductBtn.setBackground(new java.awt.Color(102, 255, 102));
        saveProductBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveProductBtn.setText("Save");
        saveProductBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveProductBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveProductBtnMouseExited(evt);
            }
        });
        saveProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductBtnActionPerformed(evt);
            }
        });

        updateProductBtn.setBackground(new java.awt.Color(204, 255, 153));
        updateProductBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateProductBtn.setText("Update");
        updateProductBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateProductBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateProductBtnMouseExited(evt);
            }
        });
        updateProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 102, 102));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtnMouseExited(evt);
            }
        });
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        categoryCmbBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        categoryCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Premium", "Deluxe", "Savory", "Kottu", "Savory Other", "Hot-Dogs", "Bavarages" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Category");

        descriptionTxtBox.setColumns(20);
        descriptionTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        descriptionTxtBox.setRows(5);
        jScrollPane1.setViewportView(descriptionTxtBox);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Description");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pNameTxtBox)
                            .addComponent(pIDTxtBox)
                            .addComponent(priceTxtBox)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clearBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateProductBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveProductBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryCmbBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pIDTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(5, 5, 5)
                .addComponent(categoryCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearBtn)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 280, 590));

        jPanel5.setBackground(new java.awt.Color(245, 222, 179));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Product Details");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        productDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Name", "Description", "Price", "Category", "Availability"
            }
        ));
        productDetailsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productDetailsTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(productDetailsTable);

        serachNameBtn.setBackground(new java.awt.Color(102, 255, 102));
        serachNameBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        serachNameBtn.setText("Search");
        serachNameBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serachNameBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serachNameBtnMouseExited(evt);
            }
        });
        serachNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serachNameBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Name");

        spNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        spNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spNameTxtBoxActionPerformed(evt);
            }
        });
        spNameTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spNameTxtBoxKeyTyped(evt);
            }
        });

        deleteProductBtntBtn.setBackground(new java.awt.Color(255, 102, 102));
        deleteProductBtntBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteProductBtntBtn.setText("Delete");
        deleteProductBtntBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteProductBtntBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteProductBtntBtnMouseExited(evt);
            }
        });
        deleteProductBtntBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductBtntBtnActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        addIngreBtn.setBackground(new java.awt.Color(64, 224, 208));
        addIngreBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        addIngreBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_ingredients_24px.png"))); // NOI18N
        addIngreBtn.setText("  Add Ingredients");
        addIngreBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addIngreBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addIngreBtnMouseExited(evt);
            }
        });
        addIngreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngreBtnActionPerformed(evt);
            }
        });

        categoryCmbBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        categoryCmbBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular Donut", "Premium Donut", "Deluxe Donut", "Savory Donut", "Kottu", "Savory Other", "Hot-Dogs", "Bavarages" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Category");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(deleteProductBtntBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(addIngreBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(serachNameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spNameTxtBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(categoryCmbBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryCmbBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serachNameBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteProductBtntBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addIngreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 10, 660, 590));

        menuPanel.setBackground(new java.awt.Color(210, 180, 140));
        menuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(210, 180, 140));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));

        updateProfileBtn.setBackground(new java.awt.Color(255, 239, 153));
        updateProfileBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateProfileBtn.setText("Update Profile");
        updateProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseExited(evt);
            }
        });
        updateProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileBtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_businessman_40px.png"))); // NOI18N

        uNameLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uNameLable.setText("Branch Manager Name");
        uNameLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        uIDLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uIDLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uIDLable.setText("Branch Manager Id");
        uIDLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uIDLable, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(uIDLable, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(uNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 140));

        assignTaskBtn.setBackground(new java.awt.Color(64, 224, 208));
        assignTaskBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        assignTaskBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_task_24px.png"))); // NOI18N
        assignTaskBtn.setText(" Assign Tasks");
        assignTaskBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                assignTaskBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                assignTaskBtnMouseExited(evt);
            }
        });
        assignTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignTaskBtnActionPerformed(evt);
            }
        });
        menuPanel.add(assignTaskBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 300, 30));

        bulkOrderBtn.setBackground(new java.awt.Color(64, 224, 208));
        bulkOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bulkOrderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_purchase_order_24px.png"))); // NOI18N
        bulkOrderBtn.setText(" Bulk Order Details");
        bulkOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bulkOrderBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bulkOrderBtnMouseExited(evt);
            }
        });
        bulkOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulkOrderBtnActionPerformed(evt);
            }
        });
        menuPanel.add(bulkOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 300, 30));

        productDetailsBtn.setBackground(new java.awt.Color(51, 204, 255));
        productDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        productDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_box_24px.png"))); // NOI18N
        productDetailsBtn.setText(" Products Details");
        productDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productDetailsBtnMouseExited(evt);
            }
        });
        productDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(productDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 300, 30));

        billTerminaBtn2.setBackground(new java.awt.Color(64, 224, 208));
        billTerminaBtn2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        billTerminaBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_bill_24px.png"))); // NOI18N
        billTerminaBtn2.setText(" Billing Terminal");
        billTerminaBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billTerminaBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billTerminaBtn2MouseExited(evt);
            }
        });
        billTerminaBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billTerminaBtn2ActionPerformed(evt);
            }
        });
        menuPanel.add(billTerminaBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 300, 30));

        sendNoteBtn.setBackground(new java.awt.Color(64, 224, 208));
        sendNoteBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        sendNoteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_notification_24px.png"))); // NOI18N
        sendNoteBtn.setText(" Send Notifications");
        sendNoteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendNoteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendNoteBtnMouseExited(evt);
            }
        });
        sendNoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendNoteBtnActionPerformed(evt);
            }
        });
        menuPanel.add(sendNoteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 300, 30));

        empDetailsBtn.setBackground(new java.awt.Color(64, 224, 208));
        empDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        empDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_employee_24px.png"))); // NOI18N
        empDetailsBtn.setText("Employee Details");
        empDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empDetailsBtnMouseExited(evt);
            }
        });
        empDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(empDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 300, 30));

        viewLogBtn.setBackground(new java.awt.Color(64, 224, 208));
        viewLogBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        viewLogBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_logs_folder_24px.png"))); // NOI18N
        viewLogBtn.setText(" View Log Sheets");
        viewLogBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewLogBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewLogBtnMouseExited(evt);
            }
        });
        viewLogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLogBtnActionPerformed(evt);
            }
        });
        menuPanel.add(viewLogBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 300, 30));

        markExpencessBtn.setBackground(new java.awt.Color(64, 224, 208));
        markExpencessBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        markExpencessBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_expensive_price_24px.png"))); // NOI18N
        markExpencessBtn.setText(" Mark Expencess");
        markExpencessBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                markExpencessBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                markExpencessBtnMouseExited(evt);
            }
        });
        markExpencessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markExpencessBtnActionPerformed(evt);
            }
        });
        menuPanel.add(markExpencessBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 300, 30));

        logOutBtn.setBackground(new java.awt.Color(255, 153, 153));
        logOutBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtnMouseExited(evt);
            }
        });
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        menuPanel.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 140, 20));

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_left_arrow_24px.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        menuPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 140, 20));

        clockInBtn.setBackground(new java.awt.Color(153, 255, 153));
        clockInBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_clock_checked_24px.png"))); // NOI18N
        clockInBtn.setText(" Mark Clock in");
        clockInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockInBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockInBtnMouseExited(evt);
            }
        });
        clockInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockInBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 300, 30));

        clockOffBtn.setBackground(new java.awt.Color(255, 102, 102));
        clockOffBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockOffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_alarm_off_24px.png"))); // NOI18N
        clockOffBtn.setText(" Mark Clock off");
        clockOffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseExited(evt);
            }
        });
        clockOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockOffBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockOffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 300, 30));

        jPanel1.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseClicked
        this.setExtendedState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLableMouseClicked

    private void minimizeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseEntered
        minimizeLable.setOpaque(true);
        minimizeLable.setBackground(new Color(210, 180, 140));
        minimizeLable.repaint();
    }//GEN-LAST:event_minimizeLableMouseEntered

    private void minimizeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseExited
        minimizeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_minimizeLableMouseExited

    private void closeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseClicked
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to exit?") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeLableMouseClicked

    private void closeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseEntered
        closeLable.setOpaque(true);
        closeLable.setBackground(new Color(210, 180, 140));
        closeLable.repaint();
    }//GEN-LAST:event_closeLableMouseEntered

    private void closeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseExited
        closeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_closeLableMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;
        int x = getLocation().x + xMoved;
        int y = getLocation().y + yMoved;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanel3MousePressed

    private void serachNameBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serachNameBtnMouseEntered
        serachNameBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_serachNameBtnMouseEntered

    private void serachNameBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serachNameBtnMouseExited
        serachNameBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_serachNameBtnMouseExited

    private void serachNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serachNameBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serachNameBtnActionPerformed

    private void spNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spNameTxtBoxActionPerformed

    private void deleteProductBtntBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteProductBtntBtnMouseEntered
        deleteProductBtntBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_deleteProductBtntBtnMouseEntered

    private void deleteProductBtntBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteProductBtntBtnMouseExited
        deleteProductBtntBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_deleteProductBtntBtnMouseExited

    private void deleteProductBtntBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductBtntBtnActionPerformed
        DefaultTableModel df = (DefaultTableModel) productDetailsTable.getModel();

        if (productDetailsTable.getSelectedRowCount() == 1) {

            JFrame f = new JFrame();
            if (JOptionPane.showConfirmDialog(f, "Do you want to delete this product") == JOptionPane.YES_NO_OPTION) {
                Product pdct = new Product();
                pdct.setProductID(df.getValueAt(productDetailsTable.getSelectedRow(), 0).toString());
                pdct.removeProduct();
                loadProducts("");
                incrementPId();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Product to delete");
        }
    }//GEN-LAST:event_deleteProductBtntBtnActionPerformed

    private void pIDTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pIDTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pIDTxtBoxActionPerformed

    private void pNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameTxtBoxActionPerformed

    private void priceTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtBoxActionPerformed

    private void saveProductBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveProductBtnMouseEntered
        saveProductBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_saveProductBtnMouseEntered

    private void saveProductBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveProductBtnMouseExited
        saveProductBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_saveProductBtnMouseExited

    private void updateProductBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProductBtnMouseEntered
        updateProductBtn.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_updateProductBtnMouseEntered

    private void updateProductBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProductBtnMouseExited
        updateProductBtn.setBackground(new Color(204, 255, 153));
    }//GEN-LAST:event_updateProductBtnMouseExited

    private void updateProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductBtnActionPerformed
        String pid = pIDTxtBox.getText();
        String name = pNameTxtBox.getText();
        String price = priceTxtBox.getText();
        String category = categoryCmbBox.getSelectedItem().toString();
        String description = descriptionTxtBox.getText();

        if (name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Product name");
            pIDTxtBox.grabFocus();
        } else if (price.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Product price");
            priceTxtBox.grabFocus();
        } else if (description.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Product Description");
            descriptionTxtBox.grabFocus();
        } else {

            Product pdct = new Product(pid, name, category, description, Double.parseDouble(price));
            pdct.updateProduct();
            incrementPId();
            loadProducts("");

        }
    }//GEN-LAST:event_updateProductBtnActionPerformed

    private void clearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseEntered
        clearBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clearBtnMouseEntered

    private void clearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseExited
        clearBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clearBtnMouseExited

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        pNameTxtBox.setText("");
        priceTxtBox.setText("");
        buttonGroup1.clearSelection();
        descriptionTxtBox.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void updateProfileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseEntered
        updateProfileBtn.setBackground(new Color(255, 255, 153));
    }//GEN-LAST:event_updateProfileBtnMouseEntered

    private void updateProfileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseExited
        updateProfileBtn.setBackground(new Color(255, 239, 153));
    }//GEN-LAST:event_updateProfileBtnMouseExited

    private void updateProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateProfileBtnActionPerformed

    private void assignTaskBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignTaskBtnMouseEntered
        assignTaskBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_assignTaskBtnMouseEntered

    private void assignTaskBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignTaskBtnMouseExited
        assignTaskBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_assignTaskBtnMouseExited

    private void assignTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignTaskBtnActionPerformed
        this.dispose();
        new BmAssignTaskFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_assignTaskBtnActionPerformed

    private void bulkOrderBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bulkOrderBtnMouseEntered
        bulkOrderBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_bulkOrderBtnMouseEntered

    private void bulkOrderBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bulkOrderBtnMouseExited
        bulkOrderBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_bulkOrderBtnMouseExited

    private void bulkOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulkOrderBtnActionPerformed
        this.dispose();
        new BulkOrderDetailsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_bulkOrderBtnActionPerformed

    private void productDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productDetailsBtnMouseEntered
        productDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_productDetailsBtnMouseEntered

    private void productDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productDetailsBtnMouseExited

    }//GEN-LAST:event_productDetailsBtnMouseExited

    private void productDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productDetailsBtnActionPerformed

    }//GEN-LAST:event_productDetailsBtnActionPerformed

    private void billTerminaBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn2MouseEntered
        billTerminaBtn2.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_billTerminaBtn2MouseEntered

    private void billTerminaBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn2MouseExited
        billTerminaBtn2.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_billTerminaBtn2MouseExited

    private void billTerminaBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billTerminaBtn2ActionPerformed
        this.dispose();
        new BillingFrame(8,uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_billTerminaBtn2ActionPerformed

    private void sendNoteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendNoteBtnMouseEntered
        sendNoteBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_sendNoteBtnMouseEntered

    private void sendNoteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendNoteBtnMouseExited
        sendNoteBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_sendNoteBtnMouseExited

    private void sendNoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendNoteBtnActionPerformed
        this.dispose();
        new SendNotificationsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_sendNoteBtnActionPerformed

    private void empDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empDetailsBtnMouseEntered
        empDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_empDetailsBtnMouseEntered

    private void empDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empDetailsBtnMouseExited
        empDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_empDetailsBtnMouseExited

    private void empDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empDetailsBtnActionPerformed
        this.dispose();
        new EmpDetailsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_empDetailsBtnActionPerformed

    private void viewLogBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewLogBtnMouseEntered
        viewLogBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_viewLogBtnMouseEntered

    private void viewLogBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewLogBtnMouseExited
        viewLogBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_viewLogBtnMouseExited

    private void viewLogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLogBtnActionPerformed
        this.dispose();
        new ViewLogSheets(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_viewLogBtnActionPerformed

    private void markExpencessBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_markExpencessBtnMouseEntered
        markExpencessBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_markExpencessBtnMouseEntered

    private void markExpencessBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_markExpencessBtnMouseExited
        markExpencessBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_markExpencessBtnMouseExited

    private void markExpencessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markExpencessBtnActionPerformed
        this.dispose();
        new BMExpenceFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_markExpencessBtnActionPerformed

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        User user = new User();
        int result = user.logOut();
        if (result == JOptionPane.YES_NO_OPTION) {
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new BranchManagerProfile(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addIngreBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addIngreBtnMouseEntered
        addIngreBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_addIngreBtnMouseEntered

    private void addIngreBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addIngreBtnMouseExited
        addIngreBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_addIngreBtnMouseExited

    private void addIngreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIngreBtnActionPerformed
        this.dispose();
        new AddIngredientsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_addIngreBtnActionPerformed

    private void clockInBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseEntered
        clockInBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_clockInBtnMouseEntered

    private void clockInBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseExited
        clockInBtn.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_clockInBtnMouseExited

    private void clockInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockInBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clok off time") == JOptionPane.YES_NO_OPTION) {

            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());
            timeSheet.setClockoffTime(LocalTime.now());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.markClockoff();

        }
    }//GEN-LAST:event_clockInBtnActionPerformed

    private void clockOffBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseEntered
        clockOffBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clockOffBtnMouseEntered

    private void clockOffBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseExited
        clockOffBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clockOffBtnMouseExited

    private void clockOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockOffBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clok off time") == JOptionPane.YES_NO_OPTION) {

            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());
            timeSheet.setClockoffTime(LocalTime.now());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.markClockoff();

        }
    }//GEN-LAST:event_clockOffBtnActionPerformed

    private void saveProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductBtnActionPerformed
        String pid = pIDTxtBox.getText();
        String name = pNameTxtBox.getText();
        String price = priceTxtBox.getText();
        String category = categoryCmbBox.getSelectedItem().toString();
        String description = descriptionTxtBox.getText();

        if (name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Product name");
            pIDTxtBox.grabFocus();
        } else if (price.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Product price");
            priceTxtBox.grabFocus();
        } else if (description.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Product Description");
            descriptionTxtBox.grabFocus();
        } else {

            Product pdct = new Product(pid, name, category, description, Double.parseDouble(price));
            pdct.addProduct();
            incrementPId();
            loadProducts("");

        }
    }//GEN-LAST:event_saveProductBtnActionPerformed

    private void priceTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTxtBoxKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_priceTxtBoxKeyTyped

    private void productDetailsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productDetailsTableMouseClicked
        DefaultTableModel df = (DefaultTableModel) productDetailsTable.getModel();

        pIDTxtBox.setText(df.getValueAt(productDetailsTable.getSelectedRow(), 0).toString());
        pNameTxtBox.setText(df.getValueAt(productDetailsTable.getSelectedRow(), 1).toString());
        descriptionTxtBox.setText(df.getValueAt(productDetailsTable.getSelectedRow(), 2).toString());
        priceTxtBox.setText(df.getValueAt(productDetailsTable.getSelectedRow(), 3).toString());
        categoryCmbBox.setSelectedItem(df.getValueAt(productDetailsTable.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_productDetailsTableMouseClicked

    private void spNameTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spNameTxtBoxKeyTyped
        //loadProducts("name like ?", "%" + pNameTxtBox.getText() + "%");

        try {

            Product pdct = new Product();
            ResultSet rs = pdct.viewProduct("*", "name like ?", "%" + spNameTxtBox.getText() + "%");
            DefaultTableModel df = (DefaultTableModel) productDetailsTable.getModel();
            int rc = df.getRowCount();
            for (int i = 0; i < rc; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("product_id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("Description"));
                v.add(rs.getString("price"));
                v.add(rs.getString("Category"));
                boolean avail = rs.getBoolean("availability");
                if (avail) {
                    v.add("Available");
                } else {
                    v.add("Not-Available");
                }
                df.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_spNameTxtBoxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductDetailsFrame("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIngreBtn;
    private javax.swing.JButton assignTaskBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton billTerminaBtn2;
    private javax.swing.JButton bulkOrderBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> categoryCmbBox;
    private javax.swing.JComboBox<String> categoryCmbBox1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clockInBtn;
    private javax.swing.JButton clockOffBtn;
    private javax.swing.JLabel closeLable;
    private javax.swing.JLabel dateLable;
    private javax.swing.JButton deleteProductBtntBtn;
    private javax.swing.JTextArea descriptionTxtBox;
    private javax.swing.JButton empDetailsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton markExpencessBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minimizeLable;
    private javax.swing.JTextField pIDTxtBox;
    private javax.swing.JTextField pNameTxtBox;
    private javax.swing.JTextField priceTxtBox;
    private javax.swing.JButton productDetailsBtn;
    private javax.swing.JTable productDetailsTable;
    private javax.swing.JButton saveProductBtn;
    private javax.swing.JButton sendNoteBtn;
    private javax.swing.JButton serachNameBtn;
    private javax.swing.JTextField spNameTxtBox;
    private javax.swing.JLabel timeLable;
    private javax.swing.JLabel uIDLable;
    private javax.swing.JLabel uNameLable;
    private javax.swing.JButton updateProductBtn;
    private javax.swing.JButton updateProfileBtn;
    private javax.swing.JButton viewLogBtn;
    // End of variables declaration//GEN-END:variables
}
