/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import Classes.*;
import Others.*;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinis
 */
public class StockDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form StockDetailsFrame
     */
    static Point initialClick;

    public StockDetailsFrame(String id, String name) {
        initComponents();

        uIDLable.setText(id);
        uNameLable.setText(name);

        dateLable.setText(DateTime.showDate());
        time();
        TableUtils.setTableEditableFalse(stockTable);
        loadLog();
    }

    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    public void loadLog() {

        try {

            StockLog log = new StockLog();
            ResultSet rs = log.viewStockLog("*", "Inner join inventory_item as ii on ii.item_id = sl.item_id", "");

            DefaultTableModel df = (DefaultTableModel) stockTable.getModel();
            int rc = df.getRowCount();
            for (int i = 0; i < rc; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("sl.item_id"));
                v.add(rs.getString("ii.name"));
                v.add(rs.getString("sl.action"));
                v.add(rs.getString("sl.change_date"));
                v.add(rs.getString("sl.change_time"));
                v.add(rs.getString("sl.old_quantity"));
                v.add(rs.getString("sl.new_quantity"));
                df.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        minimizeLable = new javax.swing.JLabel();
        closeLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        itemIDTxtBox = new javax.swing.JTextField();
        searchByIdBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stockTable = new javax.swing.JTable();
        menuPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        updateProfileBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uNameLable = new javax.swing.JLabel();
        uIDLable = new javax.swing.JLabel();
        inventoryDetailsBtn = new javax.swing.JButton();
        billTerminaBtn1 = new javax.swing.JButton();
        uDetailsBtn = new javax.swing.JButton();
        setMenuBtn = new javax.swing.JButton();
        suppDetailsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        clockInBtn = new javax.swing.JButton();
        clockOffBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 222, 179));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_16px.png"))); // NOI18N
        minimizeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLableMouseExited(evt);
            }
        });
        jPanel3.add(minimizeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 1, 30, 28));

        closeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_16px.png"))); // NOI18N
        closeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLableMouseExited(evt);
            }
        });
        jPanel3.add(closeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1259, 1, 30, 28));

        timeLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 150, 30));

        dateLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        jPanel1.setBackground(new java.awt.Color(242, 224, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(245, 222, 179));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Stock Log");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        itemIDTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        itemIDTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIDTxtBoxActionPerformed(evt);
            }
        });

        searchByIdBtn.setBackground(new java.awt.Color(102, 255, 102));
        searchByIdBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchByIdBtn.setText("Search");
        searchByIdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchByIdBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchByIdBtnMouseExited(evt);
            }
        });
        searchByIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByIdBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Inventory Id");

        stockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Item id", "item Name", "action", "Change  Date", "Chnage Time", "Old Qty", "New Qty"
            }
        ));
        jScrollPane2.setViewportView(stockTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(itemIDTxtBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByIdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchByIdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemIDTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 10, 950, 590));

        menuPanel.setBackground(new java.awt.Color(210, 180, 140));
        menuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(210, 180, 140));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));

        updateProfileBtn.setBackground(new java.awt.Color(255, 239, 153));
        updateProfileBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateProfileBtn.setText("Update Profile");
        updateProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseExited(evt);
            }
        });
        updateProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileBtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_customer_40px.png"))); // NOI18N

        uNameLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uNameLable.setText("Admin Name");
        uNameLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        uIDLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uIDLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uIDLable.setText("Admin Id");
        uIDLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uIDLable, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(uIDLable, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(uNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 140));

        inventoryDetailsBtn.setBackground(new java.awt.Color(51, 204, 255));
        inventoryDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        inventoryDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_trolley_24px.png"))); // NOI18N
        inventoryDetailsBtn.setText("Inventory Details");
        inventoryDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryDetailsBtnMouseExited(evt);
            }
        });
        inventoryDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(inventoryDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 300, 40));

        billTerminaBtn1.setBackground(new java.awt.Color(64, 224, 208));
        billTerminaBtn1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        billTerminaBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_bill_24px.png"))); // NOI18N
        billTerminaBtn1.setText(" Billing Terminal");
        billTerminaBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billTerminaBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billTerminaBtn1MouseExited(evt);
            }
        });
        billTerminaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billTerminaBtn1ActionPerformed(evt);
            }
        });
        menuPanel.add(billTerminaBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 300, 40));

        uDetailsBtn.setBackground(new java.awt.Color(64, 224, 208));
        uDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_user_24px.png"))); // NOI18N
        uDetailsBtn.setText("User Details");
        uDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uDetailsBtnMouseExited(evt);
            }
        });
        uDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(uDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 300, 40));

        setMenuBtn.setBackground(new java.awt.Color(64, 224, 208));
        setMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        setMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_restaurant_menu_24px.png"))); // NOI18N
        setMenuBtn.setText("Set Menu Details");
        setMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                setMenuBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                setMenuBtnMouseExited(evt);
            }
        });
        setMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMenuBtnActionPerformed(evt);
            }
        });
        menuPanel.add(setMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 300, 40));

        suppDetailsBtn.setBackground(new java.awt.Color(64, 224, 208));
        suppDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        suppDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_supplier_24px.png"))); // NOI18N
        suppDetailsBtn.setText("Supplier Details");
        suppDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suppDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppDetailsBtnMouseExited(evt);
            }
        });
        suppDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(suppDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 300, 40));

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_left_arrow_24px.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        menuPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 140, 30));

        logOutBtn.setBackground(new java.awt.Color(255, 153, 153));
        logOutBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtnMouseExited(evt);
            }
        });
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        menuPanel.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 140, 30));

        clockInBtn.setBackground(new java.awt.Color(153, 255, 153));
        clockInBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_clock_checked_24px.png"))); // NOI18N
        clockInBtn.setText(" Mark Clock in");
        clockInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockInBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockInBtnMouseExited(evt);
            }
        });
        clockInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockInBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 300, 40));

        clockOffBtn.setBackground(new java.awt.Color(255, 102, 102));
        clockOffBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockOffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_alarm_off_24px.png"))); // NOI18N
        clockOffBtn.setText(" Mark Clock off");
        clockOffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseExited(evt);
            }
        });
        clockOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockOffBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockOffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 300, 40));

        jPanel1.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseClicked
        this.setExtendedState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLableMouseClicked

    private void minimizeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseEntered
        minimizeLable.setOpaque(true);
        minimizeLable.setBackground(new Color(210, 180, 140));
        minimizeLable.repaint();
    }//GEN-LAST:event_minimizeLableMouseEntered

    private void minimizeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseExited
        minimizeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_minimizeLableMouseExited

    private void closeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseClicked
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to exit?") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeLableMouseClicked

    private void closeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseEntered
        closeLable.setOpaque(true);
        closeLable.setBackground(new Color(210, 180, 140));
        closeLable.repaint();
    }//GEN-LAST:event_closeLableMouseEntered

    private void closeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseExited
        closeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_closeLableMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;
        int x = getLocation().x + xMoved;
        int y = getLocation().y + yMoved;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanel3MousePressed

    private void itemIDTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIDTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIDTxtBoxActionPerformed

    private void searchByIdBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByIdBtnMouseEntered
        searchByIdBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_searchByIdBtnMouseEntered

    private void searchByIdBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByIdBtnMouseExited
        searchByIdBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_searchByIdBtnMouseExited

    private void searchByIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByIdBtnActionPerformed

        try {

            StockLog log = new StockLog();
            ResultSet rs = log.viewStockLog("*", "Inner join inventory_item as ii on ii.item_id = sl.item_id", "where sl.item_id = ?", itemIDTxtBox.getText());

            DefaultTableModel df = (DefaultTableModel) stockTable.getModel();
            int rc = df.getRowCount();
            for (int i = 0; i < rc; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("sl.item_id"));
                v.add(rs.getString("ii.name"));
                v.add(rs.getString("sl.action"));
                v.add(rs.getString("sl.change_date"));
                v.add(rs.getString("sl.change_time"));
                v.add(rs.getString("sl.old_quantity"));
                v.add(rs.getString("sl.new_quantity"));
                df.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_searchByIdBtnActionPerformed

    private void updateProfileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseEntered
        updateProfileBtn.setBackground(new Color(255, 255, 153));
    }//GEN-LAST:event_updateProfileBtnMouseEntered

    private void updateProfileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseExited
        updateProfileBtn.setBackground(new Color(255, 239, 153));
    }//GEN-LAST:event_updateProfileBtnMouseExited

    private void updateProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateProfileBtnActionPerformed

    private void inventoryDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryDetailsBtnMouseEntered
        inventoryDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_inventoryDetailsBtnMouseEntered

    private void inventoryDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryDetailsBtnMouseExited

    }//GEN-LAST:event_inventoryDetailsBtnMouseExited

    private void inventoryDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryDetailsBtnActionPerformed

    }//GEN-LAST:event_inventoryDetailsBtnActionPerformed

    private void billTerminaBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn1MouseEntered
        billTerminaBtn1.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_billTerminaBtn1MouseEntered

    private void billTerminaBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn1MouseExited
        billTerminaBtn1.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_billTerminaBtn1MouseExited

    private void billTerminaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billTerminaBtn1ActionPerformed
        this.dispose();
        new BillingFrame(3,uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_billTerminaBtn1ActionPerformed

    private void uDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uDetailsBtnMouseEntered
        uDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_uDetailsBtnMouseEntered

    private void uDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uDetailsBtnMouseExited
        uDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_uDetailsBtnMouseExited

    private void uDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uDetailsBtnActionPerformed
        this.dispose();
        new UserDetailsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_uDetailsBtnActionPerformed

    private void setMenuBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMenuBtnMouseEntered
        setMenuBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_setMenuBtnMouseEntered

    private void setMenuBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMenuBtnMouseExited
        setMenuBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_setMenuBtnMouseExited

    private void setMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMenuBtnActionPerformed
        this.dispose();
        new SetMenuFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_setMenuBtnActionPerformed

    private void suppDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppDetailsBtnMouseEntered
        suppDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_suppDetailsBtnMouseEntered

    private void suppDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppDetailsBtnMouseExited
        suppDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_suppDetailsBtnMouseExited

    private void suppDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppDetailsBtnActionPerformed
        this.dispose();
        new supplierDetails(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_suppDetailsBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new InventoryDetailsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        User user = new User();
        int result = user.logOut();
        if (result == JOptionPane.YES_NO_OPTION) {
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void clockInBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseEntered
        clockInBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_clockInBtnMouseEntered

    private void clockInBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseExited
        clockInBtn.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_clockInBtnMouseExited

    private void clockInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockInBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clock In?") == JOptionPane.YES_NO_OPTION) {
            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.setClockinTime(LocalTime.now());
            timeSheet.markClockin();
        }
    }//GEN-LAST:event_clockInBtnActionPerformed

    private void clockOffBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseEntered
        clockOffBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clockOffBtnMouseEntered

    private void clockOffBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseExited
        clockOffBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clockOffBtnMouseExited

    private void clockOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockOffBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clok off time") == JOptionPane.YES_NO_OPTION) {

            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());
            timeSheet.setClockoffTime(LocalTime.now());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.markClockoff();

        }
    }//GEN-LAST:event_clockOffBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockDetailsFrame("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton billTerminaBtn1;
    private javax.swing.JButton clockInBtn;
    private javax.swing.JButton clockOffBtn;
    private javax.swing.JLabel closeLable;
    private javax.swing.JLabel dateLable;
    private javax.swing.JButton inventoryDetailsBtn;
    private javax.swing.JTextField itemIDTxtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minimizeLable;
    private javax.swing.JButton searchByIdBtn;
    private javax.swing.JButton setMenuBtn;
    private javax.swing.JTable stockTable;
    private javax.swing.JButton suppDetailsBtn;
    private javax.swing.JLabel timeLable;
    private javax.swing.JButton uDetailsBtn;
    private javax.swing.JLabel uIDLable;
    private javax.swing.JLabel uNameLable;
    private javax.swing.JButton updateProfileBtn;
    // End of variables declaration//GEN-END:variables
}
