/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import Others.*;
import Classes.*;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinis
 */
public class supplierDetails extends javax.swing.JFrame {

    /**
     * Creates new form supplierDetails
     */
    static Point initialClick;

    int supid = 0;

    public supplierDetails(String uid, String uname) {
        initComponents();
        
        uIDLable.setText(uid);
        uNameLable.setText(uname);

        dateLable.setText(DateTime.showDate());
        time();
        loadSuppliers();
        adjustTbColums();
    }

    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    public void loadSuppliers() {

        try {

            Supplier sup = new Supplier();
            ResultSet rs = sup.viewSupplier("*", "");

            DefaultTableModel df = (DefaultTableModel) supplierTable.getModel();
            int rc = df.getRowCount();
            for (int i = 0; i < rc; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector();
                String supId = rs.getString("supp_id");
                v.add(supId);

                v.add(rs.getString("fname") + " " + rs.getString("lname"));
                v.add(rs.getString("address_line1") + "," + rs.getString("address_line2"));
                v.add(rs.getString("email"));

                String contactQuery = "SELECT tele FROM supplier_contact WHERE supp_id = ?";
                ResultSet rsContacts = MyConn.search(contactQuery, supId);

                String tele1 = "";
                String tele2 = "";

                int contactIndex = 0;
                while (rsContacts.next()) {
                    if (contactIndex == 0) {
                        tele1 = rsContacts.getString("tele");
                    } else if (contactIndex == 1) {
                        tele2 = rsContacts.getString("tele");
                    }
                    contactIndex++;
                }

                rsContacts.close();

                v.add(tele1);
                v.add(tele2);
                df.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void adjustTbColums() {

        supplierTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        supplierTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        supplierTable.getColumnModel().getColumn(2).setPreferredWidth(150);
        supplierTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        supplierTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        supplierTable.getColumnModel().getColumn(4).setPreferredWidth(100);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        minimizeLable = new javax.swing.JLabel();
        closeLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fNameTxtBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        saveSupplierBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        updateSuppBtn = new javax.swing.JButton();
        suppEmailTxtBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        suppContactTxtBox01 = new javax.swing.JTextField();
        suppContactTxtBox02 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lNameTxtBox = new javax.swing.JTextField();
        addrLineTxtBox01 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        addrLineTxtBox02 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        deleteSuppBtn = new javax.swing.JButton();
        itemNameTxtBox = new javax.swing.JTextField();
        searchNameBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        updateProfileBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uNameLable = new javax.swing.JLabel();
        uIDLable = new javax.swing.JLabel();
        inventoryDetailsBtn = new javax.swing.JButton();
        billTerminaBtn1 = new javax.swing.JButton();
        uDetailsBtn = new javax.swing.JButton();
        setMenuBtn = new javax.swing.JButton();
        suppDetailsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        clockInBtn = new javax.swing.JButton();
        clockOffBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 222, 179));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_16px.png"))); // NOI18N
        minimizeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLableMouseExited(evt);
            }
        });
        jPanel3.add(minimizeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 1, 30, 28));

        closeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_16px.png"))); // NOI18N
        closeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLableMouseExited(evt);
            }
        });
        jPanel3.add(closeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1259, 1, 30, 28));

        timeLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 150, 30));

        dateLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        jPanel1.setBackground(new java.awt.Color(242, 224, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(245, 222, 179));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add / Edit Supplier");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        fNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTxtBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("First Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Address Line 01");

        saveSupplierBtn.setBackground(new java.awt.Color(102, 255, 102));
        saveSupplierBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveSupplierBtn.setText("Save Suppllier");
        saveSupplierBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveSupplierBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveSupplierBtnMouseExited(evt);
            }
        });
        saveSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSupplierBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 102, 102));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtnMouseExited(evt);
            }
        });
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        updateSuppBtn.setBackground(new java.awt.Color(204, 255, 153));
        updateSuppBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateSuppBtn.setText("Update Suppllier");
        updateSuppBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateSuppBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateSuppBtnMouseExited(evt);
            }
        });
        updateSuppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSuppBtnActionPerformed(evt);
            }
        });

        suppEmailTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        suppEmailTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppEmailTxtBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Supplier Email");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Supplier Contact(s)");

        suppContactTxtBox01.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        suppContactTxtBox01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppContactTxtBox01ActionPerformed(evt);
            }
        });
        suppContactTxtBox01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                suppContactTxtBox01KeyTyped(evt);
            }
        });

        suppContactTxtBox02.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        suppContactTxtBox02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppContactTxtBox02ActionPerformed(evt);
            }
        });
        suppContactTxtBox02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                suppContactTxtBox02KeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Last Name");

        lNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTxtBoxActionPerformed(evt);
            }
        });

        addrLineTxtBox01.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addrLineTxtBox01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrLineTxtBox01ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Address Line 02");

        addrLineTxtBox02.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addrLineTxtBox02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrLineTxtBox02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clearBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateSuppBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveSupplierBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(suppEmailTxtBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addrLineTxtBox02, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addrLineTxtBox01, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(fNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)))
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(suppContactTxtBox01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(suppContactTxtBox02, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addrLineTxtBox01, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addrLineTxtBox02, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suppEmailTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suppContactTxtBox01, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suppContactTxtBox02, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateSuppBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 350, 590));

        jPanel5.setBackground(new java.awt.Color(245, 222, 179));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Supplier Details");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Email", "Contact01", "Contact02"
            }
        ));
        supplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(supplierTable);

        deleteSuppBtn.setBackground(new java.awt.Color(255, 102, 102));
        deleteSuppBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteSuppBtn.setText("Delete");
        deleteSuppBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteSuppBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteSuppBtnMouseExited(evt);
            }
        });
        deleteSuppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSuppBtnActionPerformed(evt);
            }
        });

        itemNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        itemNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameTxtBoxActionPerformed(evt);
            }
        });

        searchNameBtn.setBackground(new java.awt.Color(102, 255, 102));
        searchNameBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchNameBtn.setText("Search");
        searchNameBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchNameBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchNameBtnMouseExited(evt);
            }
        });
        searchNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Supplier Name");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addComponent(deleteSuppBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(itemNameTxtBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchNameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchNameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteSuppBtn)
                .addGap(13, 13, 13))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 10, 590, 590));

        menuPanel.setBackground(new java.awt.Color(210, 180, 140));
        menuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(210, 180, 140));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));

        updateProfileBtn.setBackground(new java.awt.Color(255, 239, 153));
        updateProfileBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateProfileBtn.setText("Update Profile");
        updateProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateProfileBtnMouseExited(evt);
            }
        });
        updateProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileBtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_customer_40px.png"))); // NOI18N

        uNameLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uNameLable.setText("Admin Name");
        uNameLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        uIDLable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uIDLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uIDLable.setText("Admin Id");
        uIDLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uIDLable, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(uIDLable, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(uNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 140));

        inventoryDetailsBtn.setBackground(new java.awt.Color(64, 224, 208));
        inventoryDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        inventoryDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_trolley_24px.png"))); // NOI18N
        inventoryDetailsBtn.setText("Inventory Details");
        inventoryDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryDetailsBtnMouseExited(evt);
            }
        });
        inventoryDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(inventoryDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 300, 40));

        billTerminaBtn1.setBackground(new java.awt.Color(64, 224, 208));
        billTerminaBtn1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        billTerminaBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_bill_24px.png"))); // NOI18N
        billTerminaBtn1.setText(" Billing Terminal");
        billTerminaBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billTerminaBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billTerminaBtn1MouseExited(evt);
            }
        });
        billTerminaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billTerminaBtn1ActionPerformed(evt);
            }
        });
        menuPanel.add(billTerminaBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 300, 40));

        uDetailsBtn.setBackground(new java.awt.Color(64, 224, 208));
        uDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        uDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_user_24px.png"))); // NOI18N
        uDetailsBtn.setText("User Details");
        uDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uDetailsBtnMouseExited(evt);
            }
        });
        uDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(uDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 300, 40));

        setMenuBtn.setBackground(new java.awt.Color(64, 224, 208));
        setMenuBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        setMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_restaurant_menu_24px.png"))); // NOI18N
        setMenuBtn.setText("Set Menu Details");
        setMenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                setMenuBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                setMenuBtnMouseExited(evt);
            }
        });
        setMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMenuBtnActionPerformed(evt);
            }
        });
        menuPanel.add(setMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 300, 40));

        suppDetailsBtn.setBackground(new java.awt.Color(51, 204, 255));
        suppDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        suppDetailsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_supplier_24px.png"))); // NOI18N
        suppDetailsBtn.setText("Supplier Details");
        suppDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suppDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppDetailsBtnMouseExited(evt);
            }
        });
        suppDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppDetailsBtnActionPerformed(evt);
            }
        });
        menuPanel.add(suppDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 300, 40));

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_left_arrow_24px.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        menuPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 140, 30));

        logOutBtn.setBackground(new java.awt.Color(255, 153, 153));
        logOutBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtnMouseExited(evt);
            }
        });
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        menuPanel.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 140, 30));

        clockInBtn.setBackground(new java.awt.Color(153, 255, 153));
        clockInBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_clock_checked_24px.png"))); // NOI18N
        clockInBtn.setText(" Mark Clock in");
        clockInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockInBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockInBtnMouseExited(evt);
            }
        });
        clockInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockInBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 300, 40));

        clockOffBtn.setBackground(new java.awt.Color(255, 102, 102));
        clockOffBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        clockOffBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_alarm_off_24px.png"))); // NOI18N
        clockOffBtn.setText(" Mark Clock off");
        clockOffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clockOffBtnMouseExited(evt);
            }
        });
        clockOffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockOffBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clockOffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 300, 40));

        jPanel1.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseClicked
        this.setExtendedState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLableMouseClicked

    private void minimizeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseEntered
        minimizeLable.setOpaque(true);
        minimizeLable.setBackground(new Color(210, 180, 140));
        minimizeLable.repaint();
    }//GEN-LAST:event_minimizeLableMouseEntered

    private void minimizeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseExited
        minimizeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_minimizeLableMouseExited

    private void closeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseClicked
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to exit?") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeLableMouseClicked

    private void closeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseEntered
        closeLable.setOpaque(true);
        closeLable.setBackground(new Color(210, 180, 140));
        closeLable.repaint();
    }//GEN-LAST:event_closeLableMouseEntered

    private void closeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseExited
        closeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_closeLableMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;
        int x = getLocation().x + xMoved;
        int y = getLocation().y + yMoved;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanel3MousePressed

    private void fNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTxtBoxActionPerformed

    private void saveSupplierBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveSupplierBtnMouseEntered
        saveSupplierBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_saveSupplierBtnMouseEntered

    private void saveSupplierBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveSupplierBtnMouseExited
        saveSupplierBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_saveSupplierBtnMouseExited

    private void clearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseEntered
        clearBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clearBtnMouseEntered

    private void clearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseExited
        clearBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clearBtnMouseExited

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        fNameTxtBox.setText("");
        lNameTxtBox.setText("");
        addrLineTxtBox01.setText("");
        addrLineTxtBox02.setText("");
        suppContactTxtBox01.setText("");
        suppContactTxtBox02.setText("");
        suppEmailTxtBox.setText("");
        fNameTxtBox.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void updateSuppBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateSuppBtnMouseEntered
        updateSuppBtn.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_updateSuppBtnMouseEntered

    private void updateSuppBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateSuppBtnMouseExited
        updateSuppBtn.setBackground(new Color(204, 255, 153));
    }//GEN-LAST:event_updateSuppBtnMouseExited

    private void updateSuppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSuppBtnActionPerformed
        String fname = fNameTxtBox.getText();
        String lname = lNameTxtBox.getText();
        String addres1 = addrLineTxtBox01.getText();
        String addres2 = addrLineTxtBox02.getText();
        String email = suppEmailTxtBox.getText();
        String ctn1 = suppContactTxtBox01.getText();
        String ctn2 = suppContactTxtBox02.getText();

        if (supid == 0) {
            JOptionPane.showMessageDialog(null, "Cannot Perform this action");
        } else {
            if (fname.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter First Name");
                fNameTxtBox.grabFocus();
            } else if (lname.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter Last Name");
                lNameTxtBox.grabFocus();
            } else if (addres1.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter Address line 01");
                addrLineTxtBox01.grabFocus();
            } else if (addres2.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter Address line 02");
                addrLineTxtBox02.grabFocus();
            } else if (email.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter Email");
                suppEmailTxtBox.grabFocus();
            } else if (ctn1.trim().isEmpty() || ctn2.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter Email");
                suppContactTxtBox01.grabFocus();
                suppContactTxtBox02.grabFocus();
            } else {

                Supplier supplier = new Supplier(fname, lname, addres1, addres2, email, ctn1);
                supplier.setSupId(supid);
                supplier.updateSupplier(ctn2);
                loadSuppliers();

            }
        }
    }//GEN-LAST:event_updateSuppBtnActionPerformed

    private void deleteSuppBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteSuppBtnMouseEntered
        deleteSuppBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_deleteSuppBtnMouseEntered

    private void deleteSuppBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteSuppBtnMouseExited
        deleteSuppBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_deleteSuppBtnMouseExited

    private void deleteSuppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSuppBtnActionPerformed
        if (supid == 0) {
            JOptionPane.showMessageDialog(null, "Please select a Supplier to delete");
        } else {

            JFrame f = new JFrame();
            if (JOptionPane.showConfirmDialog(f, "Do you want to delete this supplier") == JOptionPane.YES_NO_OPTION) {

                Supplier supplier = new Supplier();
                supplier.setSupId(supid);
                supplier.removeSupplier();
                loadSuppliers();

            }

        }
    }//GEN-LAST:event_deleteSuppBtnActionPerformed

    private void itemNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTxtBoxActionPerformed

    private void searchNameBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchNameBtnMouseEntered
        searchNameBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_searchNameBtnMouseEntered

    private void searchNameBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchNameBtnMouseExited
        searchNameBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_searchNameBtnMouseExited

    private void searchNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNameBtnActionPerformed

    private void suppEmailTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppEmailTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppEmailTxtBoxActionPerformed

    private void suppContactTxtBox01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppContactTxtBox01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppContactTxtBox01ActionPerformed

    private void suppContactTxtBox02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppContactTxtBox02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppContactTxtBox02ActionPerformed

    private void suppContactTxtBox01KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_suppContactTxtBox01KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (suppContactTxtBox01.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_suppContactTxtBox01KeyTyped

    private void suppContactTxtBox02KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_suppContactTxtBox02KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (suppContactTxtBox02.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_suppContactTxtBox02KeyTyped

    private void updateProfileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseEntered
        updateProfileBtn.setBackground(new Color(255, 255, 153));
    }//GEN-LAST:event_updateProfileBtnMouseEntered

    private void updateProfileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileBtnMouseExited
        updateProfileBtn.setBackground(new Color(255, 239, 153));
    }//GEN-LAST:event_updateProfileBtnMouseExited

    private void updateProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateProfileBtnActionPerformed

    private void inventoryDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryDetailsBtnMouseEntered
        inventoryDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_inventoryDetailsBtnMouseEntered

    private void inventoryDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryDetailsBtnMouseExited
        inventoryDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_inventoryDetailsBtnMouseExited

    private void inventoryDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryDetailsBtnActionPerformed
        this.dispose();
        new InventoryDetailsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_inventoryDetailsBtnActionPerformed

    private void billTerminaBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn1MouseEntered
        billTerminaBtn1.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_billTerminaBtn1MouseEntered

    private void billTerminaBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTerminaBtn1MouseExited
        billTerminaBtn1.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_billTerminaBtn1MouseExited

    private void billTerminaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billTerminaBtn1ActionPerformed
        this.dispose();
        new BillingFrame(3,uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_billTerminaBtn1ActionPerformed

    private void uDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uDetailsBtnMouseEntered
        uDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_uDetailsBtnMouseEntered

    private void uDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uDetailsBtnMouseExited
        uDetailsBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_uDetailsBtnMouseExited

    private void uDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uDetailsBtnActionPerformed
        this.dispose();
        new UserDetailsFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_uDetailsBtnActionPerformed

    private void setMenuBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMenuBtnMouseEntered
        setMenuBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_setMenuBtnMouseEntered

    private void setMenuBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMenuBtnMouseExited
        setMenuBtn.setBackground(new Color(64, 224, 208));
    }//GEN-LAST:event_setMenuBtnMouseExited

    private void setMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMenuBtnActionPerformed
        this.dispose();
        new SetMenuFrame(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_setMenuBtnActionPerformed

    private void suppDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppDetailsBtnMouseEntered
        suppDetailsBtn.setBackground(new Color(51, 204, 255));
    }//GEN-LAST:event_suppDetailsBtnMouseEntered

    private void suppDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppDetailsBtnMouseExited

    }//GEN-LAST:event_suppDetailsBtnMouseExited

    private void suppDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppDetailsBtnActionPerformed

    }//GEN-LAST:event_suppDetailsBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new AdminProfile(uIDLable.getText(), uNameLable.getText()).setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        User user = new User();
        int result = user.logOut();
        if (result == JOptionPane.YES_NO_OPTION) {
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void lNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTxtBoxActionPerformed

    private void addrLineTxtBox01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrLineTxtBox01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrLineTxtBox01ActionPerformed

    private void addrLineTxtBox02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrLineTxtBox02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrLineTxtBox02ActionPerformed

    private void clockInBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseEntered
        clockInBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_clockInBtnMouseEntered

    private void clockInBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockInBtnMouseExited
        clockInBtn.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_clockInBtnMouseExited

    private void clockInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockInBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clock In?") == JOptionPane.YES_NO_OPTION) {
            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.setClockinTime(LocalTime.now());
            timeSheet.markClockin();
        }
    }//GEN-LAST:event_clockInBtnActionPerformed

    private void clockOffBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseEntered
        clockOffBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clockOffBtnMouseEntered

    private void clockOffBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockOffBtnMouseExited
        clockOffBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clockOffBtnMouseExited

    private void clockOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockOffBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to mark Clok off time") == JOptionPane.YES_NO_OPTION) {

            TimeSheet timeSheet = new TimeSheet();
            timeSheet.setUserID(uIDLable.getText());
            timeSheet.setClockoffTime(LocalTime.now());

            DateTimeFormatter dateFormater = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            timeSheet.setDate(LocalDate.parse(dateLable.getText(), dateFormater));

            timeSheet.markClockoff();

        }
    }//GEN-LAST:event_clockOffBtnActionPerformed

    private void saveSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSupplierBtnActionPerformed
        String fname = fNameTxtBox.getText();
        String lname = lNameTxtBox.getText();
        String addres1 = addrLineTxtBox01.getText();
        String addres2 = addrLineTxtBox02.getText();
        String email = suppEmailTxtBox.getText();
        String ctn1 = suppContactTxtBox01.getText();
        String ctn2 = suppContactTxtBox02.getText();

        if (fname.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter First Name");
            fNameTxtBox.grabFocus();
        } else if (lname.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Last Name");
            lNameTxtBox.grabFocus();
        } else if (addres1.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Address line 01");
            addrLineTxtBox01.grabFocus();
        } else if (addres2.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Address line 02");
            addrLineTxtBox02.grabFocus();
        } else if (email.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Email");
            suppEmailTxtBox.grabFocus();
        } else if (ctn1.trim().isEmpty() || ctn2.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Email");
            suppContactTxtBox01.grabFocus();
            suppContactTxtBox02.grabFocus();
        } else {

            Supplier supplier = new Supplier(fname, lname, addres1, addres2, email, ctn1);
            supplier.addsupplier(ctn2);
            loadSuppliers();

        }
    }//GEN-LAST:event_saveSupplierBtnActionPerformed

    private void supplierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierTableMouseClicked
        DefaultTableModel df = (DefaultTableModel) supplierTable.getModel();

        supid = Integer.parseInt(df.getValueAt(supplierTable.getSelectedRow(), 0).toString());
        String supName = df.getValueAt(supplierTable.getSelectedRow(), 1).toString();
        String nameSplit[] = supName.split(" ");
        fNameTxtBox.setText(nameSplit[0]);
        lNameTxtBox.setText(nameSplit[1]);

        String supAddr = df.getValueAt(supplierTable.getSelectedRow(), 2).toString();
        String addrSplit[] = supAddr.split(",");
        addrLineTxtBox01.setText(addrSplit[0]);
        addrLineTxtBox02.setText(addrSplit[1]);

        suppEmailTxtBox.setText(df.getValueAt(supplierTable.getSelectedRow(), 3).toString());
        suppContactTxtBox01.setText(df.getValueAt(supplierTable.getSelectedRow(), 4).toString());
        suppContactTxtBox02.setText(df.getValueAt(supplierTable.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_supplierTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplierDetails("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrLineTxtBox01;
    private javax.swing.JTextField addrLineTxtBox02;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton billTerminaBtn1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clockInBtn;
    private javax.swing.JButton clockOffBtn;
    private javax.swing.JLabel closeLable;
    private javax.swing.JLabel dateLable;
    private javax.swing.JButton deleteSuppBtn;
    private javax.swing.JTextField fNameTxtBox;
    private javax.swing.JButton inventoryDetailsBtn;
    private javax.swing.JTextField itemNameTxtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lNameTxtBox;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel minimizeLable;
    private javax.swing.JButton saveSupplierBtn;
    private javax.swing.JButton searchNameBtn;
    private javax.swing.JButton setMenuBtn;
    private javax.swing.JTextField suppContactTxtBox01;
    private javax.swing.JTextField suppContactTxtBox02;
    private javax.swing.JButton suppDetailsBtn;
    private javax.swing.JTextField suppEmailTxtBox;
    private javax.swing.JTable supplierTable;
    private javax.swing.JLabel timeLable;
    private javax.swing.JButton uDetailsBtn;
    private javax.swing.JLabel uIDLable;
    private javax.swing.JLabel uNameLable;
    private javax.swing.JButton updateProfileBtn;
    private javax.swing.JButton updateSuppBtn;
    // End of variables declaration//GEN-END:variables
}
