/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagementsystem;

import Others.*;
import Classes.*;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinis
 */
public class UpdateProfileFrame extends javax.swing.JFrame {

    /**
     * Creates new form UpdateProfileFrame
     */
    static Point initialClick;

    int frameNo;
    String uname;
    String uid;
    int otp = 0;

    public UpdateProfileFrame(int frameNo, String uid, String uname) {
        initComponents();

        this.frameNo = frameNo;
        this.uid = uid;
        this.uname = uname;
        dateLable.setText(DateTime.showDate());
        time();
        loadUsers();
        UserIdTxtBox.disable();
        IdPwdTxtBox.disable();

    }

    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    public void loadUsers() {

        try {

            User user = new User();

            ResultSet rs = user.viewUser("*", "user_id = ?", uid);

            String id = "";
            String fname = "";
            String lname = "";
            String email = "";
            String te1e1 = "";
            String tele2 = "";
            String addr1 = "";
            String addr2 = "";
            String nic = "";

            while (rs.next()) {

                id = (rs.getString("user_id"));

                fname = (rs.getString("fname"));
                lname = (rs.getString("lname"));
                email = (rs.getString("email"));

                String contactQuery = "SELECT tele FROM User_contact WHERE user_id = ?";
                ResultSet rsContacts = MyConn.search(contactQuery, uid);

                int contactIndex = 0;
                while (rsContacts.next()) {
                    if (contactIndex == 0) {
                        te1e1 = rsContacts.getString("tele");
                    } else if (contactIndex == 1) {
                        tele2 = rsContacts.getString("tele");
                    }
                    contactIndex++;
                }
                rsContacts.close();
                addr1 = (rs.getString("address_line1"));
                addr2 = (rs.getString("address_line2"));
                nic = (rs.getString("nic"));

            }

            UserIdTxtBox.setText(id);
            fNameTxtBox.setText(fname);
            lNameTxtBox.setText(lname);
            emailTxtBox.setText(email);
            contactTxtBox02.setText(tele2);
            contactTxtBox01.setText(te1e1);
            addrLineTxtBox1.setText(addr1);
            addrLineTxtBox1.setText(addr2);
            nicTxtBox.setText(nic);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        minimizeLable = new javax.swing.JLabel();
        closeLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UserIdTxtBox = new javax.swing.JTextField();
        nicTxtBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        vChkBox = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addrLineTxtBox2 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        emailTxtBox = new javax.swing.JTextField();
        contactTxtBox01 = new javax.swing.JTextField();
        contactTxtBox02 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        IdPwdTxtBox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        newPasswordTxtBox = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        otpTxtBox = new javax.swing.JTextField();
        getOTPBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        savePwdBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        updateDetailsBtn = new javax.swing.JButton();
        clearBtn1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        fNameTxtBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lNameTxtBox = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        addrLineTxtBox1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 222, 179));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_16px.png"))); // NOI18N
        minimizeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLableMouseExited(evt);
            }
        });
        jPanel3.add(minimizeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 1, 30, 28));

        closeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_16px.png"))); // NOI18N
        closeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLableMouseExited(evt);
            }
        });
        jPanel3.add(closeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1259, 1, 30, 28));

        timeLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 150, 30));

        dateLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        jPanel1.setBackground(new java.awt.Color(242, 224, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(245, 222, 179));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Change Password");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 450, 37));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("ID");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        UserIdTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UserIdTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIdTxtBoxActionPerformed(evt);
            }
        });
        jPanel4.add(UserIdTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, 50));

        nicTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nicTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicTxtBoxActionPerformed(evt);
            }
        });
        nicTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nicTxtBoxKeyTyped(evt);
            }
        });
        jPanel4.add(nicTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 250, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Address Line 02");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        vChkBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vChkBox.setText("V");
        vChkBox.setToolTipText("Add v at the end of nic");
        jPanel4.add(vChkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("NIC");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        addrLineTxtBox2.setColumns(20);
        addrLineTxtBox2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addrLineTxtBox2.setRows(5);
        jScrollPane1.setViewportView(addrLineTxtBox2);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 490, 120));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Email");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 70, -1));

        emailTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        emailTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtBoxActionPerformed(evt);
            }
        });
        jPanel4.add(emailTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 250, 50));

        contactTxtBox01.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contactTxtBox01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTxtBox01ActionPerformed(evt);
            }
        });
        contactTxtBox01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactTxtBox01KeyTyped(evt);
            }
        });
        jPanel4.add(contactTxtBox01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 250, 50));

        contactTxtBox02.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contactTxtBox02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTxtBox02ActionPerformed(evt);
            }
        });
        contactTxtBox02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactTxtBox02KeyTyped(evt);
            }
        });
        jPanel4.add(contactTxtBox02, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 250, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Contact(s)");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jPanel2.setBackground(new java.awt.Color(245, 222, 179));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IdPwdTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        IdPwdTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdPwdTxtBoxActionPerformed(evt);
            }
        });
        jPanel2.add(IdPwdTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 450, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("User ID");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("New Password");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        newPasswordTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        newPasswordTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordTxtBoxActionPerformed(evt);
            }
        });
        jPanel2.add(newPasswordTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 450, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("OTP");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        otpTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        otpTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpTxtBoxActionPerformed(evt);
            }
        });
        jPanel2.add(otpTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 340, 40));

        getOTPBtn.setBackground(new java.awt.Color(204, 255, 153));
        getOTPBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getOTPBtn.setText("Get OTP");
        getOTPBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                getOTPBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                getOTPBtnMouseExited(evt);
            }
        });
        getOTPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getOTPBtnActionPerformed(evt);
            }
        });
        jPanel2.add(getOTPBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 100, 40));

        clearBtn.setBackground(new java.awt.Color(255, 102, 102));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtnMouseExited(evt);
            }
        });
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel2.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 450, 30));

        savePwdBtn.setBackground(new java.awt.Color(102, 255, 102));
        savePwdBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savePwdBtn.setText("Save Details");
        savePwdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                savePwdBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                savePwdBtnMouseExited(evt);
            }
        });
        savePwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePwdBtnActionPerformed(evt);
            }
        });
        jPanel2.add(savePwdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 294, 450, 40));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 470, 390));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Update Profile");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 18, 1250, 37));

        updateDetailsBtn.setBackground(new java.awt.Color(204, 255, 153));
        updateDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateDetailsBtn.setText("Update Details");
        updateDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateDetailsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateDetailsBtnMouseExited(evt);
            }
        });
        updateDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetailsBtnActionPerformed(evt);
            }
        });
        jPanel4.add(updateDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 570, 50));

        clearBtn1.setBackground(new java.awt.Color(255, 102, 102));
        clearBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn1.setText("Clear");
        clearBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtn1MouseExited(evt);
            }
        });
        clearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn1ActionPerformed(evt);
            }
        });
        jPanel4.add(clearBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 170, 50));

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_left_arrow_24px.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel4.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 210, 30));

        logOutBtn.setBackground(new java.awt.Color(255, 153, 153));
        logOutBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtnMouseExited(evt);
            }
        });
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        jPanel4.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 130, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("First Name");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        fNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTxtBoxActionPerformed(evt);
            }
        });
        jPanel4.add(fNameTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 490, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Last Name");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        lNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTxtBoxActionPerformed(evt);
            }
        });
        jPanel4.add(lNameTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 470, 50));

        addrLineTxtBox1.setColumns(20);
        addrLineTxtBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addrLineTxtBox1.setRows(5);
        jScrollPane2.setViewportView(addrLineTxtBox1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 490, 120));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Address Line 01");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1270, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseClicked
        this.setExtendedState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLableMouseClicked

    private void minimizeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseEntered
        minimizeLable.setOpaque(true);
        minimizeLable.setBackground(new Color(210, 180, 140));
        minimizeLable.repaint();
    }//GEN-LAST:event_minimizeLableMouseEntered

    private void minimizeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLableMouseExited
        minimizeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_minimizeLableMouseExited

    private void closeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseClicked
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "Do you want to exit?") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeLableMouseClicked

    private void closeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseEntered
        closeLable.setOpaque(true);
        closeLable.setBackground(new Color(210, 180, 140));
        closeLable.repaint();
    }//GEN-LAST:event_closeLableMouseEntered

    private void closeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLableMouseExited
        closeLable.setBackground(new Color(245, 222, 179));
    }//GEN-LAST:event_closeLableMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;
        int x = getLocation().x + xMoved;
        int y = getLocation().y + yMoved;
        setLocation(x, y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanel3MousePressed

    private void UserIdTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIdTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIdTxtBoxActionPerformed

    private void nicTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicTxtBoxActionPerformed

    private void emailTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtBoxActionPerformed

    private void contactTxtBox01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTxtBox01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTxtBox01ActionPerformed

    private void contactTxtBox02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTxtBox02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTxtBox02ActionPerformed

    private void getOTPBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getOTPBtnMouseEntered
        getOTPBtn.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_getOTPBtnMouseEntered

    private void getOTPBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getOTPBtnMouseExited
        getOTPBtn.setBackground(new Color(204, 255, 153));
    }//GEN-LAST:event_getOTPBtnMouseExited

    private void getOTPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getOTPBtnActionPerformed
        try {
            
            User user = new User();
            ResultSet rs = user.viewUser("email", "user_id = ?", uid);
            String email = "";
            if (rootPaneCheckingEnabled) {
                email = rs.getString("email");
            }
            
            otp = Generator.generateOTP();
            Emailer.sendOTP(otp, email, uname);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_getOTPBtnActionPerformed

    private void clearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseEntered
        clearBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_clearBtnMouseEntered

    private void clearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseExited
        clearBtn.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_clearBtnMouseExited

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        IdPwdTxtBox.setText("");
        newPasswordTxtBox.setText("");
        otpTxtBox.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void IdPwdTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdPwdTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdPwdTxtBoxActionPerformed

    private void newPasswordTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordTxtBoxActionPerformed

    private void otpTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otpTxtBoxActionPerformed

    private void updateDetailsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateDetailsBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_updateDetailsBtnMouseEntered

    private void updateDetailsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateDetailsBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_updateDetailsBtnMouseExited

    private void updateDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetailsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateDetailsBtnActionPerformed

    private void clearBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtn1MouseEntered

    private void clearBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtn1MouseExited

    private void clearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn1ActionPerformed
        fNameTxtBox.setText("");
        lNameTxtBox.setText("");
        nicTxtBox.setText("");
        contactTxtBox01.setText("");
        contactTxtBox02.setText("");
        addrLineTxtBox1.setText("");
        addrLineTxtBox2.setText("");
        emailTxtBox.setText("");
        vChkBox.setSelected(false);
    }//GEN-LAST:event_clearBtn1ActionPerformed

    private void savePwdBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savePwdBtnMouseEntered
        savePwdBtn.setBackground(new Color(0, 204, 102));
    }//GEN-LAST:event_savePwdBtnMouseEntered

    private void savePwdBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savePwdBtnMouseExited
        savePwdBtn.setBackground(new Color(102, 255, 102));
    }//GEN-LAST:event_savePwdBtnMouseExited

    private void savePwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePwdBtnActionPerformed
        if (newPasswordTxtBox.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter new Password");
        } else if (otp == 0) {
            JOptionPane.showMessageDialog(null, "Please get the OTP");
        }else {
        
            try {
                
                String upPassword = "Update user set password = ? where user_id = ?";
                int result = MyConn.save(upPassword, newPasswordTxtBox.getText(), uid);
                
                if (result == 1) {
                    JOptionPane.showMessageDialog(null, "SuccessFull");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed");
                }
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        
        }
    }//GEN-LAST:event_savePwdBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        switch (frameNo) {
            case 1:
                this.dispose();
                new EmployeeProfile(uid, uname).setVisible(true);
                break;
            case 2:
                this.dispose();
                new chefProfile(uid, uname).setVisible(true);
                break;
            case 3:
                this.dispose();
                new AdminProfile(uid, uname).setVisible(true);
                break;
            case 4:
                this.dispose();
                new HeadChefProfile(uid, uname).setVisible(true);
                break;
            case 5:
                this.dispose();
                new SupervisorProfile(uid, uname).setVisible(true);
                break;
            case 6:
                this.dispose();
                new HRProfile(uid, uname).setVisible(true);
                break;
            case 7:
                this.dispose();
                new AccountantProfile(uid, uname).setVisible(true);
                break;
            case 8:
                this.dispose();
                new BranchManagerProfile(uid, uname).setVisible(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        User user = new User();
        int result = user.logOut();
        if (result == JOptionPane.YES_NO_OPTION) {
            this.dispose();
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void contactTxtBox01KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactTxtBox01KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (contactTxtBox01.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_contactTxtBox01KeyTyped

    private void contactTxtBox02KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactTxtBox02KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (contactTxtBox02.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_contactTxtBox02KeyTyped

    private void nicTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTxtBoxKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }

        if (nicTxtBox.getText().trim().length() == 13) {
            evt.consume();
        }
    }//GEN-LAST:event_nicTxtBoxKeyTyped

    private void fNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTxtBoxActionPerformed

    private void lNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTxtBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProfileFrame(0, "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdPwdTxtBox;
    private javax.swing.JTextField UserIdTxtBox;
    private javax.swing.JTextArea addrLineTxtBox1;
    private javax.swing.JTextArea addrLineTxtBox2;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clearBtn1;
    private javax.swing.JLabel closeLable;
    private javax.swing.JTextField contactTxtBox01;
    private javax.swing.JTextField contactTxtBox02;
    private javax.swing.JLabel dateLable;
    private javax.swing.JTextField emailTxtBox;
    private javax.swing.JTextField fNameTxtBox;
    private javax.swing.JButton getOTPBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lNameTxtBox;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLabel minimizeLable;
    private javax.swing.JTextField newPasswordTxtBox;
    private javax.swing.JTextField nicTxtBox;
    private javax.swing.JTextField otpTxtBox;
    private javax.swing.JButton savePwdBtn;
    private javax.swing.JLabel timeLable;
    private javax.swing.JButton updateDetailsBtn;
    private javax.swing.JCheckBox vChkBox;
    // End of variables declaration//GEN-END:variables
}
